### ISSUE TITLE
Pressing Button for testing connection causes error

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.influxdb#118]
Admin 5.1.9 with new React UI
Influxdb Adapter 2.0.0
influx database 2.0.7

Bug:
If button "test connection" is pressed the following error is shown
![grafik](https://user-images.githubusercontent.com/25422320/124323497-b4789e80-db81-11eb-8a48-c8cdd805a42d.png)

Discussion in forum: https://forum.iobroker.net/topic/46098/test-adapter-influxdb-2-0/10

Output vom debug log 

```
influxdb.0 2021-07-02 00:17:37.004	debug	PING OK
influxdb.0 2021-07-02 00:17:29.186	debug	sendTo "test" to system.adapter.admin.0 from system.adapter.influxdb.0
influxdb.0 2021-07-02 00:17:29.039	debug	TEST DB Version: undefined
influxdb.0 2021-07-02 00:17:29.034	debug	Incoming message test from system.adapter.admin.0
influxdb.0 2021-07-02 00:17:22.005	debug	PING OK

```

Settings in influx adapter are correct. In log is visible that adater is able to connect to database.

Expected behaviour:
Connection test response with positive response if settings are correct

**Comment by Apollon77** [comment]
Please install anew from GitHub ... restart dapter manually afterwards and try again please

**Comment by Feuer-sturm** [comment]
@Apollon77 Issue is fixed. Thank you :-)

**Comment by Apollon77** [comment]
Thanks go to @Excodibur :-)
