### ISSUE TITLE
Prevent Admin5 Error

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.influxdb#119]
Admin 5.1.9 with new React UI
Influxdb Adapter 2.0.0
influx database 2.0.7

Bug:
After pressing button to delete all data in database a window with an error is shown and data are not deleted

![grafik](https://user-images.githubusercontent.com/25422320/124324524-64024080-db83-11eb-83ac-dbc9e5ac9741.png)

![grafik](https://user-images.githubusercontent.com/25422320/124324722-ba6f7f00-db83-11eb-8380-0d84d20854b7.png)

Log

```
influxdb.0 | 2021-07-02 22:22:53.596 | debug | sendTo "destroy" to system.adapter.admin.0 from system.adapter.influxdb.0
influxdb.0 | 2021-07-02 22:22:53.594 | error | true
influxdb.0 | 2021-07-02 22:22:53.592 | error | HttpError: id must have a length of 16 bytes
influxdb.0 | 2021-07-02 22:22:53.571 | info | Dropping database iobroker for orgId f45f9f6c8fa4515e
influxdb.0 | 2021-07-02 22:22:53.568 | debug | Incoming message destroy from system.adapter.admin.0
influxdb.0 | 2021-07-02 22:22:45.818 | debug | PING OK
```

Steps to reproduce
- Open Influx Instance
- Press Button "Alle Daten in Datenbank löschen"
- Check raw values in database

**Comment by Apollon77** [comment]
@Feuer-sturm Yes, this is a new feature from Admin and basically only sql has support for these "editing features" right now ... so tis is more a "add support for it" as Feature request :-) But I would see that as secnd step ... lets have a stable 2.0.0 f adapter and then we can see to add also the new data editing options (if this is that easy with Influxdb)

**Comment by Feuer-sturm** [comment]
@Apollon77 Thanks for the feedback. It can be a solution to disable the button until the feature is implemented, just to avoid confusions.

**Comment by Apollon77** [comment]
This would be an Admin Feature ticket then :-)) (but admin can not detect that right now ...

**Comment by Feuer-sturm** [comment]
Than let's wait that the feature is implemented in influxdb :-)

**Comment by Feuer-sturm** [comment]
Just installed current github version. Now it is possible to use the button to delete data in the database.
