### ISSUE TITLE
no option to choose which db version I use

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.influxdb#123]
hello

so I wanted to switch vom history adapter to influxdb.

so i installed influxdb 2 without any problems and it runs.

then I installed the adapter - version 1.9.5 - but then I hit a wall.
in the documentation it said I should choose the db version - but there is no option for that.

please see screenshot,
I use admin 5.1.9 - even on "use old ui" there is absolutely no option.
also where do I get authentication token? in the readme it simple says "The Owner Token was generated on InfluxDB setup process." but where do I get it, where is it saved and so on?

<img width="1256" alt="Bildschirmfoto 2021-07-09 um 20 10 21" src="https://user-images.githubusercontent.com/27220902/125120391-b21ec300-e0f2-11eb-8f3e-62909a6f82d5.png">

**Comment by Apollon77** [comment]
duplicate #45 ... InfluxDB 2.0 support  is currently in alpha test, see forum link

**Comment by krobipd** [comment]
thanks for the information

that a little confusion because the adapter information says

"The Adapter supports InfluxDB 1.x and 2.x" 

so I assumed it works with version 2.

**Comment by Apollon77** [comment]
Check the changelog ... you will see a version WORK IN PROGRESS where 2.x supprort is in, but yes Readme in "forward in time"
