### ISSUE TITLE
influxdb 2.0 - Verarbeitung Retention Wert

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.influxdb#126]
Admin 5.1.15
influxdb2.0 Adapter: Githubversion mit dem Stand vom "Commits on Jul 29, 2021"

Folgende 

# Szenario a) Keine automatische Löschung
In der Instanz ist "keine automatische Löschung" ausgewählt und dies sehe ich auch in Influxdb
![grafik](https://user-images.githubusercontent.com/25422320/127574247-cfbf0f3b-6bf7-49bb-8eb5-bdfda431b3ac.png)

Wenn ich dann den Wert auf 1 Jahr im Adapter setze kommt keine Abfrage mit der Bestätigung.
![grafik](https://user-images.githubusercontent.com/25422320/127574277-8998773a-61a6-481d-be39-cdc2a264217c.png)

Nach Beenden und speichern wir 1 Jahr auch in Influx übernommen
![grafik](https://user-images.githubusercontent.com/25422320/127574317-e7746dec-86d3-4d54-b5a4-d9c6adfe9f22.png)

Erwartung: Abfrage zur Bestätigung erscheint vor der Übernahme

# Szenario b) Retention: 365 days
Wenn jetzt 1 Jahr in ioBroker und influxdb hinterlegt ist und ich dann 3 Monate z.B. einstelle
![grafik](https://user-images.githubusercontent.com/25422320/127574382-9af148ec-e7bb-4f19-aef7-859961529706.png)

aber die Bestätigung nicht anklicke und nur beenden und speichern drücke, dann wird trotzdem der Wert in influxdb geändert
![grafik](https://user-images.githubusercontent.com/25422320/127574392-cad02147-6bab-4941-b198-63018554e09b.png)

Erwartung: Beenden und schließen verwirft die vorgenommene Einstellung es wird keine Änderung in influxdb übernommen.

**Comment by Excodibur** [comment]
Danke für das Melden des Bugs!

Testfälle:
1. Hier scheint noch ein Fehler im Adapter-Code zu sein. Passe ich zeitnah an.
2. Dieser Fehler hängt mit einem Bug im Admin zusammen (https://github.com/ioBroker/ioBroker.admin/issues/1035). Hier steht noch ein Fix aus. Eigentlich sollte das "Speichern" Feld ausgegraut werden, solange die Checkbox nicht aktiviert wurde, aber das funktioniert im Moment leider noch nicht.

**Comment by Apollon77** [comment]
@Feuer-sturm please retry Github

**Comment by Feuer-sturm** [comment]
@Excodibur Danke für die schnelle Umsetzung.

Problem a) ist gelöst aber jetzt ist defaultmäßig die Checkbox aktiviert. Wenn der Anwender jetzt auf speichern drückt bekommt er  keine Warnung.
![grafik](https://user-images.githubusercontent.com/25422320/127721471-6e52cc78-e91e-41f1-9a7b-13a15ba4da3b.png)

Erwartung: Die Checkbox sollte hier nicht automatisch aktiv sein.


Problem b)
Ist im Zusammenspiel mit Admin 5.1.17 gelöst. Wenn die Checkbox nicht aktiv ist, sind die Speichern Schaltflächen nicht auswählbar.

Kommt der rote Rand um die Schaltflächen von Admin 5.1.17 oder vom influxdb Adapter?

![grafik](https://user-images.githubusercontent.com/25422320/127721577-bbbb1c92-cebb-430d-b1f9-01b706e349d1.png)

**Comment by Excodibur** [comment]
Bei Szenario a) hast du Recht, dass scheint noch ein Problem zu sein. Ich schaue gerade, wie es sich beheben lässt.

Der Rote Rand bei b) kommt vom Admin 5. Ist etwas seltsam um den "Schliesen"-Dialog, aber müsste an ggf. dort in einem Ticket nochmal klären.

**Comment by Excodibur** [comment]
Bitte nochmal neu von Github ziehen und probieren. Fix für a) sollte jetzt drin sein.

**Comment by Feuer-sturm** [comment]
@Excodibur danke. Werde ich in den nächsten Tagen machen.

**Comment by Feuer-sturm** [comment]
Admin 5.1.19
influxdb: aktuelle Github Version  Jul 31, 2021
@Excodibur 
Ich hab mir die aktuelle Github Version installiert. 

Szenario a) ist noch nicht gefixt. Es ist weiterhin sofort die Checkbox aktiviert, wenn ich von unendlich auf eine Zeitspanne umstelle


Szenario b)
Ich gehe davon aus, dass der rote Rahmen ein Hinweis darauf sein soll, dass eine Vorbedingung (Checkbox nicht aktiviert) nicht erfüllt ist.
@GermanBluefox Ist meine Vermutung richtig und somit: "works as designed"?

**Comment by Excodibur** [comment]
@Feuer-sturm: a) kann ich bei mir leider nicht reproduzieren. Nach dem Speichern von Einstellungen ist die Checkbox bei mir wieder im Ausgangszustand (nicht aktiviert). Lediglich wenn ich auf eine niedrigere Retention wechsle, die Checkbox aktiviere, dann auf eine höhere und dann wieder eine niedrigere (also alles ohne zu Speichern), aber da sehe ich kein Problem, wenn die Checkbox innerhalb des selben Konfigurationsvorgangs aktiviert bleibt. Ich teste im Chrome.

**Comment by Feuer-sturm** [comment]
@Excodibur 
zu a)
Bei mir sah es gerade beim testen so aus. 
![Animation17](https://user-images.githubusercontent.com/25422320/127782396-459a91b3-f288-4b60-986f-20e20fd8c141.gif)

Nachdem ich jetzt speichern beim Test ausgewählt habe und wenn ich dann beim einstellen eine neue niedrigen Zeit auswähle ist wie von dir beschrieben die Checkbox nicht aktiv.

Es lag vermutlich daran, dass ich von einer älteren Github Version kam und seitdem keine neue Retentionzeit gespeichert habe.

Somit sollte Punkt a) ja mit einem offiziellen Release gelöst sein.
