### ISSUE TITLE
Adapter crashes if there is a timeout > ~1 min

### ISSUE THREAD

**Issue by josefzahner** [ioBroker/ioBroker.influxdb#138]
I'm using the newest adapter 2.10 with influxdb 2. My iobroker runs on a NAS and my iobroker on a Raspberry Pi. In between those two guys is a router. Sometimes I have to restart this router, which takes several minutes. After 1 minute or so the adapter throws a "Request timed out" message and starts to restart multiple times until iobroker warns that the adapter has done too many restarts and stops it -> at the end I've to log in to the iobroker admin gui and restart the adapter in such a case. Please either fix the crash or let the user deside how long the Connection Timeout from iobroker to influxdb should be.

Logfile (connection issue starts at about 09:11:05 2021-08-10)
[iobroker.2021-08-10.zip](https://github.com/ioBroker/ioBroker.influxdb/files/6961578/iobroker.2021-08-10.zip)

**Comment by Apollon77** [comment]
@josefzahner Can you pleasde install new Github version (version number stay same, so manually restart adapter after update please) ... and try to repro?

**Comment by Feuer-sturm** [comment]
Mit der neuen Github Version kommt jetzt nur der zyklische Error, dass keine Verbindung zur Datenbank mögilch ist.

```
11 Aug 2021 21:44:26.327
influxdb.0 (29293) Not connected to InfluxDB, try later
11 Aug 2021 21:44:22.774
influxdb.0 (29293) Error: connect EHOSTUNREACH 192.168.178.101:8086
11 Aug 2021 21:44:19.693
influxdb.0 (29293) Connecting to InfluxDB 2
11 Aug 2021 21:44:19.691
influxdb.0 (29293) Influx DB Version used: 2.x
11 Aug 2021 21:44:19.689
influxdb.0 (29293) Connecting http://192.168.178.101:8086 ... 
```

**Comment by Apollon77** [comment]
Und Funktion ist wieder hergestellt wenn Verbindung wieder da ist? Dann wäre das ja ok

**Comment by josefzahner** [comment]
I've just tested the new version and it works now as it should. 
I've disconnected the InfluxDB from the iobroker adapter for more than 15min and I just got the already mentioned "EHOSTUNREACH" messages. Perfect. After the reconnect it starts sending the data again.

**Comment by Feuer-sturm** [comment]
Mit Influx Datenbank 1.8.0 und 2.0.7  wird die Verbindung auch wieder hergestellt und die gepufferten Einträge wurden auch wieder geschrieben

**Comment by Apollon77** [comment]
perfect, then we go Beta tomorrow
