### ISSUE TITLE
Password needs to be reentered

### ISSUE THREAD

**Issue by ichtyp** [ioBroker/ioBroker.influxdb#142]
Hey there, 

i just updated from 1.9.5. to 2.1.1 and wanted to let you know that i had to reenter the password for the db connection, otherwise i got errors over and over again "No connection to DB".
Is that an expected behaviour?

I found that hint in the log: 
error: influxdb.0 (45438) Password error: Please re-enter the password in Admin. Stopping

Now it works fine again.

**Comment by Excodibur** [comment]
Yes, this is expected, as with 2.1.1 we changed the Adapter to store _Password_ (or for Influx 2 _Token_) in an encrypted form, to enhance security. Unfortunately for password set with older releases (that are stored unencrypted) a one-time reentering is needed.

**Comment by Excodibur** [comment]
@KLVN Your problem is different from this issue, but already reported here: https://github.com/ioBroker/ioBroker.influxdb/issues/145

**Comment by KLVN** [comment]
> @KLVN Your problem is different from this issue, but already reported here: #145

Ah, sorry. Originally came for the issue with the password and just noticed this next issue, without looking for it on GitHub first 😬
