### ISSUE TITLE
Number is string and bool

### ISSUE THREAD

**Issue by Marsx79** [ioBroker/ioBroker.influxdb#143]
At Adapter 2.0.0 is no error.

Influx Adapter 2.1.1
Error in query "from(bucket: "ioBroker") |> range(start: 2021-07-31T22:00:00.000Z, stop: 2021-08-14T19:40:00.000Z) |> filter(fn: (r) => r["_measurement"] == "Aussenfuehler") |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") |> group() |> limit(n: 500)": HttpError: runtime error @1:236-1:243: group: schema collision detected: column "ack" is both of type string and bool

**Comment by Apollon77** [comment]
Hm ... This is strange .. can you try to select the data that are string? Because normally ack is ALWAYS and EVER a boolean!

Where these string values vcome from? This more seems to be an issue in your data somehow ... interesting

@Excodibur FYI

**Comment by Marsx79** [comment]
It´s from the "ems-esp Adapter"

> {
  "type": "state",
  "common": {
    "id": "system.sensors.temperatures.outdoor_t1",
    "name": "km200:system.sensors.temperatures.outdoor_t1",
    "type": "number",
    "unit": "°C",
    "read": true,
    "write": false,
    "role": "value.temperature",
    "alias": {
      "id": "ems-esp.0.system.sensors.temperatures.outdoor_t1"
    },
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "storageType": "Number",
        "aliasId": "Aussenfuehler",
        "changesOnly": false,
        "debounce": 1000,
        "changesRelogInterval": 0,
        "changesMinDelta": 0
      }
    }
  },
  "native": {},
  "_id": "alias.0.Heizung.Allgemein.Aussentemperatur",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1627938517347
}

**Comment by Apollon77** [comment]
Hm ... I checked there but in GitHub all ack values are boolean, maybe check that you use the latest verison or check with the dev ... delete all data please
