### ISSUE TITLE
After Upgrade to 2.1.1: Error: error authorizing query: iouser not authorized to execute statement

### ISSUE THREAD

**Issue by tmycgn** [ioBroker/ioBroker.influxdb#145]
After updating the adapter from 1.9.5 to 2.1.1 I constantly get the following error message in log:

`(5178) Error: error authorizing query: iouser not authorized to execute statement 'ALTER RETENTION POLICY autogen ON iobroker DURATION 0s REPLICATION 1 SHARD DURATION 1w DEFAULT', requires admin priv`

The user was created according to the manual. The adapter worked without problems until now. After downgrading again to 1.9.5 everything works fine again.

**Comment by Apollon77** [comment]
In versions >1.9.5 the retention was never really set other then initially, now the retention is tried to be set as defined. 

In your case the adapter detected a different retention policy set as you defined in the adapter.

Please give the user proper rights so that adapter can fix the retention or adjust the setting in iobroker to match your retention policy.

@Excodibur maybe enhance the docs for influxdb1 with "whcih rights are needed"?

**Comment by tmycgn** [comment]
@Apollon77 Thanks for the prompt answer, could you possibly tell me with which commands I can implement this? I thought this was just done with

`GRANT ALL ON "iobroker" TO "user"`

**Comment by Apollon77** [comment]
it is the "holzhammer" method, but will work I guess :-)

**Comment by Excodibur** [comment]
To be honest I did not check it fully for Influx 1.x yet, but I assume it will be something like:
```
-- grant db level permissions so the adapter can create a new database, if needed and alter the permissions
GRANT [CREATE RETENTION POLICY,ALTER RETENTION POLICY,CREATE DATABASE] to "<username>"
-- grant read/write (ALL) access for the database itself
GRANT ALL ON "<dbname>" to "<username"
```

I have to admit that it currently looks like the Influx 1.x code of the adapter can create new databases, but lacks the part where permissions are granted to the user to that DB. Perhaps I am missing something, but I assume most users currently don't use a user/password at all, or use some root-account that has access to all databases anyways. @Apollon77 I guess we should investigate further there.

**Comment by Apollon77** [comment]
No I think the user needs to be setup correctly, so I would just add a readme part on permissions for influxdb 1

**Comment by klein0r** [comment]
Debug-Log:

```
influxdb.0 | 2021-08-17 12:04:23.543 | error | Error: error authorizing query: iouser not authorized to execute statement 'ALTER RETENTION POLICY autogen ON iobroker DURATION 365d REPLICATION 1 SHARD DURATION 1w DEFAULT', requires admin privilege
-- | -- | -- | --
influxdb.0 | 2021-08-17 12:04:23.530 | info | Applying retention policy (autogen) for iobroker to 31536000 seconds. Shard Duration: 604800 seconds
influxdb.0 | 2021-08-17 12:04:23.530 | debug | old retention: [object Object] new retention: 31536000
influxdb.0 | 2021-08-17 12:04:23.523 | info | Connected!
influxdb.0 | 2021-08-17 12:04:23.515 | info | Influx DB Version used: 1.x
```

My idea was to set the retention policy manually (as admin).

```bash
pi@raspberrypi4:~ $ influx -username admin -password xxx
Connected to http://localhost:8086 version 1.8.5
InfluxDB shell version: 1.8.6
> ALTER RETENTION POLICY autogen ON iobroker DURATION 365d REPLICATION 1 SHARD DURATION 1w DEFAULT
> SHOW RETENTION POLICIES ON iobroker
name    duration  shardGroupDuration replicaN default
----    --------  ------------------ -------- -------
autogen 8760h0m0s 168h0m0s           1        true
```

This should lead to an exit due to the following code:

https://github.com/ioBroker/ioBroker.influxdb/blob/4c6e445570cce59bef802e89377b2516c0d43b58/lib/DatabaseInfluxDB1x.js#L78-L83

(please log `oldRetention.time` instead of the complete object in debug)

It seems like the comparison doesn't work:

https://github.com/ioBroker/ioBroker.influxdb/blob/4c6e445570cce59bef802e89377b2516c0d43b58/lib/DatabaseInfluxDB1x.js#L79

The reason is, that `oldRetention.time` is number, but `retention` is typeof string.

**Comment by Apollon77** [comment]
Please  check out GitHub version and restart adapter manually once after update. It should log it but do not block from further execution

**Comment by Diginix** [comment]
> To be honest I did not check it fully for Influx 1.x yet, but I assume it will be something like:
> 
> ```
> -- grant db level permissions so the adapter can create a new database, if needed and alter the permissions
> GRANT [CREATE RETENTION POLICY,ALTER RETENTION POLICY,CREATE DATABASE] to "<username>"
> -- grant read/write (ALL) access for the database itself
> GRANT ALL ON "<dbname>" to "<username"
> ```
> 
> I have to admit that it currently looks like the Influx 1.x code of the adapter can create new databases, but lacks the part where permissions are granted to the user to that DB. Perhaps I am missing something, but I assume most users currently don't use a user/password at all, or use some root-account that has access to all databases anyways. @Apollon77 I guess we should investigate further there.

"GRANT [CREATE RETENTION POLICY..." doesn't work for me with influxdb 1.8.9
