### ISSUE TITLE
No restore of backup

### ISSUE THREAD

**Issue by MubiTec** [ioBroker/ioBroker.influxdb#152]
new setup of iobroker. try to restore influxdb from backup. I use influxdb 1.
I tried to restore it with Backitup 2.1.13 + 2.1.17
Both times it started with "Started restore ..." but nothing happens, only this in Debug-log:

backitup.0 | 2021-08-23 10:16:07.201 | debug | sendTo "list" to system.adapter.admin.0 from system.adapter.backitup.0
-- | -- | -- | --
backitup.0 | 2021-08-23 10:16:05.087 | debug | FTP: connected.
backitup.0 | 2021-08-23 10:16:04.539 | debug | Backup list be read ...
backitup.0 | 2021-08-23 10:16:02.881 | debug | sendTo "getTelegramUser" to system.adapter.admin.0 from system.adapter.backitup.0: {"671102863":{"firstName":"Marcel","userName":"Mubitec"}}
backitup.0 | 2021-08-23 10:16:02.879 | debug | telegram-instance: telegram.0
**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
3292 MHz
Modell
Common KVM processor
RAM
7.77 GB
System-Betriebszeit
01:49:33
Node.js
v14.17.5 (Empfohlene Version v12.22.5)
NPM
6.14.14
Datenträgergröße
10.77 GB
freier Festplattenspeicher
6.88 GB
Anzahl der Adapter
436
Betriebszeit
01:49:34
Aktive Instanzen
25
location
/opt/iobroker/
Hostname
io

**Comment by Apollon77** [comment]
I would say when then this is an backitup issue or?
