### ISSUE TITLE
deprecated in Influx Log

### ISSUE THREAD

**Issue by lindi200000** [ioBroker/ioBroker.influxdb#153]
Hallo,
ich bekomme im ms-Takt folgende Meldung in die Influx Log von IOBroker.

`{"log":"[httpd] 192.168.188.60 - iobroker [24/Aug/2021:18:13:35 +0000] \"POST /write?database=iobroker\u0026db=iobroker\u0026p=%5BREDACTED%5D\u0026precision=ms\u0026u=iobroker HTTP/1.1 \" 204 0 \"-\" \"-\" ff3351e6-0506-11ec-8459-0242ac16000a 2265\n","stream":"stderr","time":"2021-08-24T18:13:35.116258096Z"}`

Ich kann mir wer sagen, durch was das kommt und wie ich das verhindere? Ich hatte dann mal eine 47GB Log Datei bis mir das aufgefallen ist :D .

Installiert war erst der Influx Adapter im Stable, nun ist der Adapter aus der latest drauf, jedoch gibt es auch hier keine Besserung.
Als Influx DB verwende ich als Docker die Version 1.8.6

Was kann man hier machen, das die Meldungen nicht mehr kommen?

VG
Lindi

**Comment by Apollon77** [comment]
Also ich tippe das du in der InfluxDB konfig das logging für die HTTP Calls aktiviert hast ... damit loggt er auch jeden Write request ... ändere das logging. 

Ich sehe da auch kein "deorecated"?? Wo istd as?

**Comment by lindi200000** [comment]
Wir haben den Teil `\u0026p=%5BREDACTED%5D\` als deprecated interpretiert. Das logging bei Docker ist Standardmäßig aktiv. ich habe es nun deaktiviert. 
Falls der oben gezeigt Ausschnitt kein Fehler ist, dann reicht ja das deaktivieren von den Logs.

**Comment by Excodibur** [comment]
Hier geht es anscheinend eher um das Logverhalten der Influx-DB und nicht um ein Adapter-spezifisches Problem, daher habe ich das Ticket mal als "invalid" markiert. Aus Adapter-Sicht können wir hier nichts machen.

Zu deiner Frage bzgl. InfluxDB:
_REDACTED_ ist in dem Fall sogar gut, weil InfluxDB hier sonst bei jedem Aufruf dein DB-Passwort im Klartext loggen würde.

Man kann InfluxDB dazu bringen die HTTP Calls wo anders hin zu loggen, d.h. von den normalen DB-Lognachrichten zu trennen, siehe auch https://docs.influxdata.com/influxdb/v1.6/administration/logs/#redirecting-http-request-logging. Ob das im Container-Kontext so einfach umzusetzen ist (z.B. DB-Config ändern über Volume-Mount, oder vielleicht tuts auch eine Umgebungsvariable), müsste man ausprobieren.
