### ISSUE TITLE
"log changes intervals" greift nur bei Haken "Nur Änderungen aufzeichnen" aktiv

### ISSUE THREAD

**Issue by stenmic** [ioBroker/ioBroker.influxdb#165]
mir ist aufgefallen, dass bei mir die Einstellung "log changes intervals" nur greift wenn der Haken bei "Nur Änderungen aufzeichnen" aktiviert ist (was ja auch Sinn macht, wenn von euch so gewollt).
Jedoch sollte dann das Feld inaktiv sein, wenn der Haken nicht gesetzt wurde.

![Image 052](https://user-images.githubusercontent.com/56360313/132103701-6090803e-c44c-4f8d-b50b-589983ba7ca4.jpg)

**Comment by Apollon77** [comment]
@Excodibur DU bist in jsonconfig tiefer drin als ich :-)

**Comment by Apollon77** [comment]
Correct, log changes interval and also min change is nly relevant if "log chages only" is used

**Comment by Apollon77** [comment]
fixed in 2.4.0
