### ISSUE TITLE
Disconnection to influx adapter

### ISSUE THREAD

**Issue by ardu1** [ioBroker/ioBroker.influxdb#168]
Hello,

I'm back from holidays and find out that my ioBroker doesn't work correct since 21.09. I got no data. The problem seems the influx adapter (v. 1.9.5), it does not connect to the database. The message I got when I try to connect is:     Error: read ECONNRESET

I tried to look for updates, but all is ok. I also tried to look for an update on GitHub.  There is a version, but the icon looks different to my actual icon?

Then I looked to the settings, the port was 8088. I tried to use the port 8086. For a moment it connected but one moment later the same error. One moment later, it connected again. Now I could also read data and see in Grafana. It seems it works. But during I write this report, the error comes again for a short moment? Then it connected again. The difference now after changing the port is that I could get data from my sensors. 
What could be the reason? And what can I do to fix it?
I made a screenshot from the error messages.

Thanks and best regards!

![image](https://user-images.githubusercontent.com/36503094/134766682-333a0f08-7fbd-4b00-a4d5-3d3f71998003.jpeg)
![image](https://user-images.githubusercontent.com/36503094/134766490-d13b554e-9414-4990-ac4f-061f91165d50.jpeg)

**Comment by Apollon77** [comment]
ECONRESET means thatthe influxdb resets the connection,
ECONNREFUSED means that the Influxdb refuses the connection. Please check Influxdb log

**Comment by ardu1** [comment]
Hello, I found the problem, in the influxdb log . Curl was after the last update not installed. I don't know why, but now after reinstall it is all ok!

Thanks!
