### ISSUE TITLE
Could not connect to influxdb Cloud - Request timed out

### ISSUE THREAD

**Issue by spitzea** [ioBroker/ioBroker.influxdb#175]
Error message:
RequestTimedOutError: Request timed out
Connecting https://eu-central-1-1.aws.cloud2.influxdata.com:8086 ...
![image](https://user-images.githubusercontent.com/91912532/135908145-7f673515-16fa-4508-be83-85046abe288d.png)

**Versions:**  
Influxdb Adapter 2.2.0
InfluxDB Cloud
JS-Controller version: 3.3.15
Node version: v12.22.6
Admin 5.1.24

DB settings:
![image](https://user-images.githubusercontent.com/91912532/135907677-bc7b2da9-cd54-4a97-8ca5-b8dac417a044.png)

The influxdb cloud is only available via https, so a port isn't required.
(Error the error occurs with Port "8086" or "0")

My guess is: The adapter attaches a port to the url even it is https and then it gets a timeout!
It's the same you try it in the browser: 
https://eu-central-1-1.aws.cloud2.influxdata.com:8086 <- timeout
https://eu-central-1-1.aws.cloud2.influxdata.com <- works fine

Direct connection works also fine:
curl --request POST "https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/write?bucket=<newbucket>&org=<me@mail.de>" --header "Authorization: Token xxxTOKENxxx"

**Comment by Apollon77** [comment]
If it is https then port should be 443 ... does that work?

**Comment by spitzea** [comment]
I changed it:
![image](https://user-images.githubusercontent.com/91912532/135920626-4564724a-c2d6-4e28-bd0e-6144d6b15bae.png)

Now I get another error message:
![image](https://user-images.githubusercontent.com/91912532/135920543-0f41e916-2e53-4550-808c-cc5722293062.png)

I double check the Organization and the token ... it is correct.

**Comment by Apollon77** [comment]
For Token please see the readme ... we till do not understand why only the "all access token" is working ... but it seems to work.
And yes it also seems that the cloud offering do not support setting shard group duration - thats why it is shown as error but the adapter is still working ...

**Comment by spitzea** [comment]
Thanks a lot for your support.
I'll ignore that error.
