### ISSUE TITLE
Entprellzeit is 0 and giving an error on every number entered

### ISSUE THREAD

**Issue by DerEmder** [ioBroker/ioBroker.influxdb#176]
Hi

if I want to add a new datapoint to influx, the Entprellzeit is set to 0 (in red). But it has been set to 1000 in the standard settings. The annoying part is - if you try to enter a number in the field, then you will get an error message for every(!) number you type in. Just ask if you need more informations.

Standard settings:

![Bildschirmfoto vom 2021-10-05 16-51-06](https://user-images.githubusercontent.com/91392202/136048166-0a9044bb-d597-4ae3-a20b-ebc3f6ac320a.jpg)

Error:

![Bildschirmfoto vom 2021-10-05 16-50-39](https://user-images.githubusercontent.com/91392202/136048244-30181cbe-79dd-46f1-a391-3dcddab34641.jpg)

My system:

**System**: ioBroker 5.1.25
**Hostname**: Casper
**Platform**: Linux arm64 @  Raspberry Pi 4
**Memory**: 4 GB
**Node.js**: 12.22.6
**NPM**: 7.24.1
**Admin Adapter**: 5.1.25
**JS-Controller**: 3.3.18
**JS Script Engine**: 5.2.13
**Z-Wave Adapter**: 2.2.0
**Zigbee Adapter**: 1.6.3
**influxDB Adapter**: 2.2.0
**MQTT Adapter**: 2.4.0 (Broker)
**Z-Wave Controller**: USB ZME-UZB1
**Zigbee Controller**: CC2652P v3.x

### Z-Wave: 

7 x Roller Shutter Controller: Fibaro FGRM-222
1 x Multisensor: Aotec MS ZW100
2 x Multisensor: DB5
4 x Multisensor: Fibaro FGMS-001
1 x Siren: Everspring SE812
1 x Water Sensor: Everspring ST812
1 x Water Sensor: Fibaro FGFS-101
3 x Dimmer: Fibaro FGD-212
2 x Main Switches: Greenwave NS310
1 x Window Sensor: Schwaiger ZHS09
1 x Smoke Detector: Vision ZS6101

### Zigbee:

1 x Mueller Color LED A60 ZBT-Extended Color
2 x Philips Hue Motion Sensor SML001
6 x Philips Hue White Single Bulb B22 LWB010
1 x Philips Hue White Ambience E14 LTW012
1 x Philips Hue White and Color LCT010
3 x Philips Hue White A60 LWA001

### WiFi:

6 x Shelly1 Switches
1 x Logitech Harmony Hub

### MQTT:

1 x Weather Station (WiFi)
1 x ESP8266 Radar Motion Sensor (WiFi)
1 x ESP8266 EMS Boiler Controller (WiFi)
1 x ESP32 Flood Sensor & LED Controller (WiFi)
1 x ESP32 Ambilight Controller @ Kodi (WiFi)
2 x 10.1" Touch Display @ Raspberry Pi 3+ (WiFi)
1 x 8" Touch Display @ Odroid C2 (OctoPi)
1 x Kodi Mediacenter @ Raspberry 3+
1 x Vero 4K Mediacenter with OSMC (Kodi)

**Comment by Diginix** [comment]
It is the same with the history adapter. Only some object types respects the default debounce setting. If you get the 0, just type 1 and if the error dialog comes press escape and type 0 and again escape until you have 1000. Then you can edit it without error. Easier is the editing of the object raw. But you have to be careful.

**Comment by DerEmder** [comment]
I don't use the history adapter. Thanks for the hint - I will edit the raw object data. Or, even better, mark the number "1000" somewhere and paste it into the field at once. That won't trigger the error message.

Anyway, I sincerely hope this annoying behauviour will be fixed.

**Comment by Diginix** [comment]
I have noticed this since Admin 5,but never opened an issue. And yes, it is a bug and should be fixed sometimes.

**Comment by Apollon77** [comment]
will be fixed in 2.4.0 soon
