### ISSUE TITLE
Multiple Bucket Support

### ISSUE THREAD

**Issue by Sp0b1e** [ioBroker/ioBroker.influxdb#177]
Is it possible to extend the adapter to support multiple buckets with different retention policies in one influxdb instance?
Or how do you group data from different adapters in the InfluxDB so that the overview and allocation in Grafana is not too confusing?

**Comment by Excodibur** [comment]
Without heavy rewriting the adapter won't support this. Is there an issue with deploying more than one instance of the influx-adapter to write data to different buckets?

If data from different buckets should appear on the same graph in Grafana you could either setup multiple queries or join data of two or more buckets in one query (https://docs.influxdata.com/influxdb/cloud/query-data/flux/join/).
