### ISSUE TITLE
adding option to disable ping/ health api when using InfluxCloud

### ISSUE THREAD

**Issue by mdax82** [ioBroker/ioBroker.influxdb#178]
**Is your feature request related to a problem? Please describe.**
Its a follow up already partially mentioned in https://github.com/ioBroker/ioBroker.influxdb/issues/175. Using this nice plugin against InfluxCloud it drops errors / reconnects every minute. 

function ping(adapter) is not able to validate and sets reconnect(adapter):

influxdb.1	2021-10-21 15:42:20.789	info	(14349) Connected!
influxdb.1	2021-10-21 15:42:20.789	debug	(14349) Storage type for metadata found in DB: none
influxdb.1	2021-10-21 15:42:20.788	debug	(14349) Result of metadata storage type check: [[{"result":"_result","table":0,"_value":"_start"},{"result":"_result","table":0,"_value":"_stop"}],[]]
influxdb.1	2021-10-21 15:42:20.668	debug	(14349) Query to execute: import "influxdata/influxdb/schema" schema.fieldKeys(bucket: "iobroker")
influxdb.1	2021-10-21 15:42:20.616	warn	(14349) HttpError: specifying shard-group duration is not supported
influxdb.1	2021-10-21 15:42:20.615	error	(14349) HttpError: specifying shard-group duration is not supported
influxdb.1	2021-10-21 15:42:20.573	debug	(14349) connected set to true
influxdb.1	2021-10-21 15:42:20.543	debug	(14349) Query to execute: import "influxdata/influxdb/schema" schema.tagKeys(bucket: "iobroker")
influxdb.1	2021-10-21 15:42:20.542	info	(14349) Applying retention policy for iobroker to 0 seconds. Shard Group Duration (calculated): 604800 seconds
influxdb.1	2021-10-21 15:42:20.538	debug	(14349) Buckets: {"links":{"self":"/api/v2/buckets?descending=false&limit=20&offset=0&orgID=XXXXXXXXXXXXXXX"},"buckets":[{"id":"XXXXXXXXXXXXXXX","orgID":"XXXXXXXXXXXXXXX","type":"system","schemaTyp
influxdb.1	2021-10-21 15:42:20.465	debug	(14349) Organizations: {"links":{"self":"/api/v2/orgs"},"orgs":[{"links":{"buckets":"/api/v2/buckets?org=XXXXXXXXXXXXXXX","dashboards":"/api/v2/dashboards?org=XXXXXXXXXXXXXXX","labels":"/api/v2/
influxdb.1	2021-10-21 15:42:20.385	debug	(14349) Organization being checked: XXXXXXXXXXXXXXX
influxdb.1	2021-10-21 15:42:20.384	info	(14349) Influx DB Version used: 2.x
influxdb.1	2021-10-21 15:42:20.384	info	(14349) Connecting https://eu-central-1-1.aws.cloud2.influxdata.com:443 ...
influxdb.1	2021-10-21 15:42:10.391	debug	(14349) connected set to false
influxdb.1	2021-10-21 15:42:10.383	debug	(14349) PING NOT OK
influxdb.1	2021-10-21 15:41:55.311	info	(14349) Connected!
influxdb.1	2021-10-21 15:41:55.311	debug	(14349) Storage type for metadata found in DB: none
influxdb.1	2021-10-21 15:41:55.310	debug	(14349) Result of metadata storage type check: [[{"result":"_result","table":0,"_value":"_start"},{"result":"_result","table":0,"_value":"_stop"}],[]]
influxdb.1	2021-10-21 15:41:55.210	debug	(14349) Query to execute: import "influxdata/influxdb/schema" schema.fieldKeys(bucket: "iobroker")
influxdb.1	2021-10-21 15:41:55.164	warn	(14349) HttpError: specifying shard-group duration is not supported
influxdb.1	2021-10-21 15:41:55.163	error	(14349) HttpError: specifying shard-group duration is not supported
influxdb.1	2021-10-21 15:41:55.101	debug	(14349) connected set to true
influxdb.1	2021-10-21 15:41:55.076	debug	(14349) Query to execute: import "influxdata/influxdb/schema" schema.tagKeys(bucket: "iobroker")
influxdb.1	2021-10-21 15:41:55.075	info	(14349) Applying retention policy for iobroker to 0 seconds. Shard Group Duration (calculated): 604800 seconds
influxdb.1	2021-10-21 15:41:55.074	debug	(14349) Buckets: {"links":{"self":"/api/v2/buckets?descending=false&limit=20&offset=0&orgID=XXXXXXXXXXXXXXX"},"buckets":[{"id":"XXXXXXXXXXXXXXX","orgID":"XXXXXXXXXXXXXXX","type":"system","schemaTyp
influxdb.1	2021-10-21 15:41:54.995	debug	(14349) Organizations: {"links":{"self":"/api/v2/orgs"},"orgs":[{"links":{"buckets":"/api/v2/buckets?org=XXXXXXXXXXXXXXX","dashboards":"/api/v2/dashboards?org=XXXXXXXXXXXXXXX","labels":"/api/v2/
influxdb.1	2021-10-21 15:41:54.908	debug	(14349) Organization being checked: XXXXXXXXXXXXXXX
influxdb.1	2021-10-21 15:41:54.905	info	(14349) Influx DB Version used: 2.x
influxdb.1	2021-10-21 15:41:54.902	info	(14349) Connecting https://eu-central-1-1.aws.cloud2.influxdata.com:443 ...
influxdb.1	2021-10-21 15:41:44.914	debug	(14349) connected set to false
influxdb.1	2021-10-21 15:41:44.901	debug	(14349) PING NOT OK
influxdb.1	2021-10-21 15:41:29.826	info	(14349) Connected!

Looking further into it root cause seem to be the ping query which uses the health API endpoint. 

As per 
https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/ping/#available-with-influxdb-oss-2x-only 

"The influx ping command works with InfluxDB OSS 2.x, but does not work with InfluxDB Cloud."

Hence ping does not receive the expected result and forces a reconnect.

**Describe the solution you'd like**
Adding a possiblity to disable ping for 2.x as adding manually 

    //disable ping
    this.ping = false;

to DatabaseInfluxDB2x.js fixes the issue.

Thank you! :)

**Comment by Apollon77** [comment]
Problem with this is that you can not detect any disconnection anymore ...

**Comment by mdax82** [comment]
The health request seems just to identify the health of the instance as per
https://docs.influxdata.com/influxdb/v2.0/api/#operation/GetHealth

so technically to identify a disconnect any other request could be used if the result can be digested in similar way.

Though for the we probably do not want to be too chatty as this goes as this counts and cost:

"How is a query execution defined?
A query execution can be broadly defined as the total number of individual queries, tasks, alert checks, and data explorer activities. More specifically it is defined as the total number of API requests coming into InfluxDB Cloud. This can include, but are not limited to, explicit query requests coming from:

InfluxDB browser clients, running features such as Data Explorer and Dashboards
InfluxDB client libraries for JavaScript, Python, Go, etc.
Third-party apps, such as Grafana
InfluxDB CLI, the command line interface run from a terminal
Queries posted via InfluxDB HTTP API, using a tool such as curl
Tasks and Alert Checks running in the InfluxDB Cloud account
Query executions include queries run both in Flux and in InfluxQL."

Probably it would be more an approach if data can not be sent, retry X times and if this still fails assume connection is dead and reconnect?

**Comment by Apollon77** [comment]
in fact there is no standing connection, but it is still the question when to buffer stuff and such ... I need to look into it when I find time

**Comment by Apollon77** [comment]
Will come ein 2.4.0 soon
