### ISSUE TITLE
Can't connect any longer to InfluxDB with new 2.2.0 version

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.influxdb#179]
**Describe the bug**  
in stable version on my prod server I still run InfluxDB Adapter with 1.9.5
On my test server I updated to the new version 2.2.0 and now the adapter can't connect any longer to my Influx DB which still runs with version 1.8.4 !

The log shows only "No connection to DB"

**To Reproduce**  
see above descritp

**Expected behavior**  
That the influxdb adapter with version 2.2.0 connects to my influx db which runs with version 1.8.4
**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.2.0
 - JS-Controller version: 3.3.18
 - Node version: 12.22.7
 - Operating system: ebian GNU/Linux 10 (buster)

**Additional context**  
no additional text needed here

**Comment by Apollon77** [comment]
And honestly ... yes missing. I will add it
