### ISSUE TITLE
callback result needed

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.influxdb#186]
I want the influxDB to filter a measurement and write it in a new measurement.
After that i want to drop the first measurement.
After that copy the new measurement into a measurement with the old name
After that delete the measurement with the new name.

Problem: all these procedeures are time sensitiv, that means when i fire all those commands, influxDB ist not ready on performing the command before...

Question: would it be possible to get a (Javascript)-callback result from the influxDB after a command has been fullfilled?
if possible wouldn't this be a nice feature?

**Comment by Apollon77** [comment]
And you want to send these requests how? Using the "query" message or how? If yes then the query command should return a callback with the result after it was executed and response was gotten from influxdb ... In fact the adapter is mainly there to stare and retriueve the data ... it is no complete "database abstraction layer" ... so maybe better write a javascript script for that using the official influxdb libs?

**Comment by Apollon77** [comment]
no answer
