### ISSUE TITLE
Ignore Zero values or implement consistency check/max allowed changes

### ISSUE THREAD

**Issue by Duese123** [ioBroker/ioBroker.influxdb#193]
**Is your feature request related to a problem? Please describe.**
i have an power meter which is sending the total kWh. Sometimes i get zero values and it will be saved in my DB. Afterwards delete the zeros in DB is not that easy like in mySQL. 

**Describe the solution you'd like**
There could be a field in the properties from the datapoint for example to ignore 0 values. OR: There is an minimal allowed difference option exististing, maybe there could be also an maximal allowed difference value. Is the value changing rate to high the new value will be ignored and will not be written in the DB. 

for example 200,202,0,203,205 .... the 0 will be ignored (if i set datachangerate max = e.g 10) and will not be written in the DB

**Comment by Apollon77** [comment]
Hm ... I would more say that you need to use a small JavaScript script to process the values and write them into a "cleaned state" where you ignore the invalid values. Implementning such checks into the adapter will be "never ending" and in my eyes "never usable for all users"

**Comment by Duese123** [comment]
yep should be than easiest way. Thanks
