### ISSUE TITLE
In getHistory request adapter returned significantly bigger time interval, then it was requested ...

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.influxdb#207]
**Describe the bug**  

Currently in this adapter in functions getHistory/getHistoryIflx2 the history data is requested from database not only inside of the time interval, received by getHistory request, but, for "smooth" drawing, one value before and one after in the appropriate timeseries...
But, in some cases, the timestamp of this "additional" data-points can be significantly differ from begin and end values(borders) of requested time interval... Up to several days ...
**To Reproduce**  
For example, I have a graph for some values in the lovelace adapter.
As history adapter the influxDB is used.
When I have big "holes" in the data time-ranges , when I trying to get graphs, which have starting point inside, the first value has significantly different timestamp, several days earlier, then the start date of the requested time interval ...
It hard to explain, but I hope the pictures will help.

There is a picture with influxdb as history adapter:
![image](https://user-images.githubusercontent.com/66964358/151610673-c8a51494-a76e-4ff6-80d2-516fd218005d.png)

There is the same graph, but with 'basic' history adapter, with the same "hole" in data
![image](https://user-images.githubusercontent.com/66964358/151610852-8524d896-0185-456e-8836-b0c76482a136.png)

In first case the first data item has timestamp of the January 15, when the start date of requested time range is January 21.

**Expected behavior**  
Explained above

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: Linux

**Additional context**

**Comment by PeterVoronov** [comment]
Appropriate [PR ](https://github.com/ioBroker/ioBroker.influxdb/pull/206)is proposed.

**Comment by PeterVoronov** [comment]
New PR is https://github.com/ioBroker/ioBroker.influxdb/pull/225

**Comment by Apollon77** [comment]
Please check in 2.5.x+ issues fixed? Or whats left?

**Comment by PeterVoronov** [comment]
> Please check in 2.5.x+ issues fixed? Or whats left?

closed, as an appropriate PR
