### ISSUE TITLE
New data points aren't created in influxdb anymore

### ISSUE THREAD

**Issue by 1N4148** [ioBroker/ioBroker.influxdb#219]
**Bug**
Activating a new data point within IOBroker doesn't create a dataset/measurement in influxdb.

**To Reproduce**  
IOBroker -> Objects -> Data point -> Gear symbol -> influx.0 -> Activate. 
Info-Log message for new data point appears
"Show measurements" on influx doesn't list the new point even after a lot of data changes

**Expected behavior**  
New data point is created in influx.

**Screenshots & Logfiles**  
No errors in any logfile found. 

**Versions:**  
 - Adapter version: 2.4.0 
 - JS-Controller version: 3.3.2
 - Node version: 14.19.0
 - Operating system: debian bullseye/amd64

**Additional context**  
It worked normally until some days ago. I've added 2 new data points, the 1st one was created, the 2nd not. Cannot add any new data points anymore. All existing data points are updated without any problems. The new added data points however show a history table & graph in IOBroker configuration page for the data point entry.

**Comment by Apollon77** [comment]
Please enable debug log and check the logs for the non working points. are settings different to the working ones?

**Comment by 1N4148** [comment]
The settings are the same. As I said, every new data point I activate isn't stored in influxdb. 

Even debug level isn't giving me any hints why the newly created data points aren't stored.

i```
nfluxdb.0` | 2022-02-06 01:06:07.722 | debug | Datatype zzzz: Currently: number, StorageType: Number
-- | -- | -- | --
influxdb.0 | 2022-02-06 01:06:07.721 | debug | Min-Delta reached zzzz, last-value=20.5, new-value=20.6, ts=1644105967719
influxdb.0 | 2022-02-06 01:06:05.195 | debug | Datatype zzzz: Currently: number, StorageType: Number
influxdb.0 | 2022-02-06 01:06:05.195 | debug | Min-Delta reached zzzz, last-value=20.8, new-value=20.5, ts=1644105965191
influxdb.0 | 2022-02-06 01:06:02.707 | debug | Datatype zzzz: Currently: number, StorageType: Number
influxdb.0 | 2022-02-06 01:06:02.707 | debug | Datatype zzzz: Currently: number, StorageType: Number
influxdb.0 | 2022-02-06 01:06:02.707 | debug | Min-Delta reached zzzz, last-value=20.7, new-value=20.8, ts=1644105962685
influxdb.0 | 2022-02-06 01:06:00.240 | debug | value not changed zzzz, last-value=20.7, new-value=20.7, ts=1644105960212
influxdb.0 | 2022-02-06 01:05:57.782 | debug | value not changed zzzz, last-value=20.7, new-value=20.7, ts=1644105957775
influxdb.0 | 2022-02-06 01:05:55.135 | debug | Datatype zzzz: Currently: number, StorageType: Number
influxdb.0 | 2022-02-06 01:05:55.134 | debug | Min-Delta reached zzzz, last-value=20.8, new-value=20.7, ts=1644105955133
influxdb.0 | 2022-02-06 01:05:52.652 | debug | Datatype zzzz: Currently: number, StorageType: Number
influxdb.0 | 2022-02-06 01:05:52.652 | debug | Min-Delta reached zzzz, last-value=20.6, new-value=20.8, ts=1644105952647


```

**Comment by Apollon77** [comment]
ok, now you can check in log for the cases where "Datatype...." is loggen what comes after it ... there should be writes in these cases, unless they are buffered for later write

**Comment by 1N4148** [comment]
I have regular writes every minute (buffered) but I cannot filter for this specific data point. 

If I add another InfluxDB-Adapter instance and connect it to a new, empty database, the all data points are created in the new database after I active them in the second instance. So I assume the problem is located in the existing influx database. But even with debug logging I cannot find anything why newly created data points aren't shown up as a measurement. Strange.

**Comment by 1N4148** [comment]
And another fact I don't understand using the influx cli:

>show measurements on iobroker
Only the "old" working data points are listed

>show measurements on _internal
All data points, even the new ones are listed

**Comment by Apollon77** [comment]
Could it be that you changed the "using tags" setting in adapter? Then - as Readme says" the data are incompatible mixed and that only works when a new database is used because data structures are different then!

**Comment by 1N4148** [comment]
Where's this setting? I cannot find it anywhere. Maybe this has been changed but by whom? I wasn't.

**Comment by Apollon77** [comment]
Option is called "Use tags to store metadata information, instead of fields" and is available one for influxdb 2.0 usage

**Comment by 1N4148** [comment]
I'm using influx 1.8.10 and adapter 2.4.0 so I don't have this setting

The problem initially appeared with influx 1.6.7 and adapter 1.9.5 when activated the new data points for a zigbee airquality sensor. The co2 data point was created in influx, the temperature & humidity data points not. Since then I wasn't able to add any new data points.

**Comment by 1N4148** [comment]
Another strange observation:
I've made a backup, restored it on a new server. The last 7 days are missing, don't know why. But I can add new data points.

**Comment by Apollon77** [comment]
Did you ever checked the influxdb logs? Maybe there was an issue there?

**Comment by 1N4148** [comment]
Yes, also checked the influx logs but didn't find any hint. Why can I add new data to existing points but cannot add new points? Why is the restored backup incomplete as the last shard (7 days) is not restored?

I don't have absolutely no clue what else to look for  :(

**Comment by 1N4148** [comment]
A small update: It looks like the last shard was somehow damaged. After a new shard started this night, the missing data point were added as measurements to the db. 

A backup & restore shows all data in the new db except the shard 244. Somehow it's stored in _internal not in iobroker. But why can I see the data with grafana in the original db but not in the restored? Still a lot of questions...

`2022/02/07 10:06:23 backing up db=iobroker rp=autogen shard=236 to influx-backup/iobroker.autogen.00236.00 since 0001-01-01T00:00:00Z
2022/02/07 10:06:23 backing up db=_internal rp=monitor shard=244 to influx-backup/_internal.monitor.00244.00 since 0001-01-01T00:00:00Z
2022/02/07 10:06:23 backing up db=iobroker rp=autogen shard=253 to influx-backup/iobroker.autogen.00253.00 since 0001-01-01T00:00:00Z
`

**Comment by Apollon77** [comment]
Hm ... but I think nothing where the adapter could do anything or?!

**Comment by 1N4148** [comment]
Cannot say what caused this. The database is used exclusively for iobroker/grafana. But I also don't know how the adapter is handling the data creation/inserts.

If this cannot be caused by the adapter we can close here.
