### ISSUE TITLE
2.5.1 is crashing on startup with Influx DB 2

### ISSUE THREAD

**Issue by souhl** [ioBroker/ioBroker.influxdb#226]
**Describe the bug**  
The adapter is crashing right after startup.

**To Reproduce**  
Installed latest adapter from GitHub to ensure Influx DB2 support.

**Expected behavior**  
No crash after start :)

**Screenshots & Logfiles**  

host.smarthome | 2022-02-18 15:57:58.343 | info | Restart adapter system.adapter.influxdb.0 because enabled
-- | -- | -- | --
host.smarthome | 2022-02-18 15:57:58.343 | error | instance system.adapter.influxdb.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.smarthome | 2022-02-18 15:57:58.343 | error | Caught by controller[1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
host.smarthome | 2022-02-18 15:57:58.343 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.influxdb/main.js:234:28
host.smarthome | 2022-02-18 15:57:58.343 | error | Caught by controller[1]: TypeError: hosts.some is not a function
host.smarthome | 2022-02-18 15:57:58.343 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
influxdb.0 | 2022-02-18 15:57:57.795 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
influxdb.0 | 2022-02-18 15:57:57.795 | info | terminating
influxdb.0 | 2022-02-18 15:57:57.791 | error | hosts.some is not a function
influxdb.0 | 2022-02-18 15:57:57.791 | error | TypeError: hosts.some is not a function at /opt/iobroker/node_modules/iobroker.influxdb/main.js:234:28 at processTicksAndRejections (internal/process/task_queues.js:97:5)
influxdb.0 | 2022-02-18 15:57:57.788 | error | unhandled promise rejection: hosts.some is not a function
influxdb.0 | 2022-02-18 15:57:57.787 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
influxdb.0 | 2022-02-18 14:57:42.778 | info | Connected!
influxdb.0 | 2022-02-18 14:57:42.751 | info | Applying retention policy for iobroker to 31536000 seconds. Shard Group Duration (calculated): 604800 seconds
influxdb.0 | 2022-02-18 14:57:42.712 | info | Influx DB Version used: 2.x
influxdb.0 | 2022-02-18 14:57:42.711 | info | Connecting http://localhost:8086 ...
influxdb.0 | 2022-02-18 14:57:42.709 | info | No stored data from last exit found

**Versions:**  
 - Adapter version: 2.5.1
 - JS-Controller version: 3.3.22
 - Node version: V12.22.10
 - Operating system: Ubuntu

**Comment by josefzahner** [comment]
Exactly the same here. I've upgrade today from 2.2.0 to 2.5.1.

**Comment by Apollon77** [comment]
Yes 2.5.1 is buggy, will check it later

**Comment by woupi** [comment]
Bei mir auch das gleiche, danke für die Mühe.

**Comment by souhl** [comment]
Just updated to 2.5.2 and it seems to be fixed.
