### ISSUE TITLE
influxdb 2.x: How to connect to db via iobroker

### ISSUE THREAD

**Issue by schluff81** [ioBroker/ioBroker.influxdb#234]
Hi,

I just installed influxdb 2.1.1 as docker on a synology. 

I provided: 
DOCKER_INFLUXDB_INIT_USERNAME: daniel
DOCKER_INFLUXDB_INIT_PASSWORD: test123test
DOCKER_INFLUXDB_INIT_ORG: tetorg
DOCKER_INFLUXDB_INIT_BUCKET: iobroker
DOCKER_INFLUXDB_INIT_MODE: setup

In iobroker I installed on the same machine (also docker) iobroker with influxdb adapter (latest: 2.6.1)

If I now enter the ip of the server (192.168.178.61) with the specified ports 8086 , the username: daniel, the password test123test,
I get a massege in the log that the username / password is wrong. 

I understand that I have to deal with a token for the organisation instead of username and password but how?

Any help is welcome

**Comment by Apollon77** [comment]
In stall the v2 version which is currently in Beta/Latest repository

**Comment by schluff81** [comment]
I installed 2.6.1.... Is that wrong? Or what v2 do u mean?
