### ISSUE TITLE
Error: connect EHOSTUNREACH 192.168.1.249:8086

### ISSUE THREAD

**Issue by Matt77CHE** [ioBroker/ioBroker.influxdb#235]
**Describe the bug**  
Since js-controller 4.0.21, there is no mor connection to influxdb....

I wrote allready in iobroker - Forum about my issue, but the only solution I got was re-enter password - but this did not work.

I also went into influx with command show databases and show users - everything was fine.
I also created a second user for iobroker database - no success to connect.

Any ideas what I could try to do?

**Comment by SlippySken** [comment]
How did you solve it?

**Comment by Apollon77** [comment]
EHOSTUNREACH means that the IP is not available in your network or can not be reachable via network routes
