### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by SiebeS91** [ioBroker/ioBroker.influxdb#245]
I have some issues after updating to the latest version.
I updated from 1.8.4 ? to the 2.6.3 and now I have some issues with the connection to my DB.
This seems to be from time to time and solves itself I would say.

[log.txt](https://github.com/ioBroker/ioBroker.influxdb/files/8479813/log.txt)

**Comment by SiebeS91** [comment]
![image](https://user-images.githubusercontent.com/94370199/163139975-67b1cb81-9519-4b8f-8bae-1b5df54f73cf.png)

**Comment by Apollon77** [comment]
Please check the log of your influxdb!

ECONNREFUSED means that the influxDB itself is not reachable. Also the ECONNRESET (where it seems to "start") is the reason that the InfluxDB resets the connection.
