### ISSUE TITLE
Vorhaltezeit einzelne Daten einstellen

### ISSUE THREAD

**Issue by JHA-2021** [ioBroker/ioBroker.influxdb#253]
Es wäre gut, wenn man die Vorhaltezeit einzelner Daten einstellen könnte, so dass die Datenbank nicht mit unwichtigen Daten unverhältnismässig aufgebläht wird.

**Comment by Apollon77** [comment]
Unterstützt die DB nicht weil die retention nur glbal pro DB eingestellt werden kann

**Comment by JHA-2021** [comment]
Ist denn ein löschen einzelner Daten nicht möglich? Dann könnte man ja selber regelmäßig eine Löschroutine laufen lassen...

**Comment by Diginix** [comment]
@Apollon77 Wo sehe ich die wirklich genutzte Retention der DB?
Hab das in der Instanz von 1 auf 2 Jahre gestellt, aber kommt die Änderung dann bei der DB überhaupt an?

**Comment by Diginix** [comment]
Ok, danke. Vllt wäre es noch eine Erweiterung wert, mehr als 2 Jahre aber nicht unbegrenzt zu ermöglichen.
Bei Wetter oder PV Daten können 3-5 Jahre Rückblick schon mal interessant sein. Bei unbegrenzt gerät das aber dann irgendwann ggf. doch außer Kontrolle.

**Comment by Apollon77** [comment]
mach ein feature request ... das ist weniger das problem zu ändern
