### ISSUE TITLE
add more predefined retention times beyond 2 years

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.influxdb#254]
Would be great to be able to choose as retention time also 3, 4 and 5 years. Not only 2 or unlimited.
Don't know whether a user defined value is possible for e.g. 7 or 10 years.

**Comment by Apollon77** [comment]
Userdefined is not that convenient because the value is in milliseconds :-) so better add some more selection options

**Comment by Apollon77** [comment]
will be in 3.0.0 ... retention can then be custom set in "number of days" ...

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/topic/54756/test-adapter-influxdb-3-0-0?_=1651862740477
