### ISSUE TITLE
Adapter 3.x.x - veränderte Datenaufzeichnung unter InfluxDB 1.x.x.

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.influxdb#259]
Adapter Version 3.0.2

Es ist eingentlich kein Issue im klassischen Sinne, sondern mehr eine Frage ob man dieses Verhalten irgendwie wieder heilen kann. Vor der Installation der 3.x.x Version stellte sich der Datensatz unter InfluxDB 1.x.x in der Darstellung mit Grafana, wie folgt da.

![image](https://user-images.githubusercontent.com/44617472/168412747-ec6340b9-6187-4ff3-8371-519109613a51.png)

Die Influxdb Datensätze dazu sahen so aus.

![image](https://user-images.githubusercontent.com/44617472/168412780-67aee8e9-6e51-4df2-94d6-68ff66451642.png)

Mit der Umstellung auf die neue Adapter Version 3.x.x. (sieht man im Diagramm am Donnerstag Mittag), haben sich die Datensätze wie folgt verändert, was im Diagramm ebenfalls zu einer anderen Darstellung (ab Donnerstag Mittag) führt.

![image](https://user-images.githubusercontent.com/44617472/168412856-2418aa51-abe0-4f9b-bf4e-65566154ccce.png)

Kann man dieses Aufzeichnungsverhalten des Adapters, durch Änderungen von Einstellungen im Adapter irgendwie wieder "heilen". 
Ein Update der Datenbank auf Influxdb 2.x.x kommt für mich derzeit nicht in Frage.

**Comment by Apollon77** [comment]
Hast Du im Forum Thread die Details gelesen zu dem was sich in dieser Major Version geändert hat? Bitte die Defaukt- und Datenounkt EInstellungen zeigen und am besten mal Debug für den Datenpunkt aktivieren und Debug für die Instanz ... dann sollte im Debug Log sehr genau zu sehen sein warum er was loggt

**Comment by Apollon77** [comment]
Checke mal Blocktime und Enprellzeit Einstellungen ...

**Comment by JBSullivan** [comment]
Habe ich schon gleich am Anfang gemacht. Obwohl ich 1000 ms eintragen hatte, stand nach dem Update bei der Entprellzeit eine 0 drin. Blocktime hatte ich nie gesetzt und die stand und steht auf 0. An der Diagrammdarstellung von Grafana bzw. den gelieferten Datenpunkten hat sich noch nichts geändert - allerdings habe ich aktuell auch kaum Zeit dem akribisch hinterher zu gehen.

**Comment by Apollon77** [comment]
Bann debug log aktivieren fürt den Datenounkt und die Instanz ... dann siehst Du was er warum loggt und warum nicht.

Zum Thema "steht auf 0" ... dann mal die Standardeinstellungen gecheckt? Vllt steht da was drin was überschreibt?

**Comment by Apollon77** [comment]
@JBSullivan ?? Any update or log?

**Comment by Apollon77** [comment]
siehe #267
