### ISSUE TITLE
Booleans are displayed as "null" value

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.influxdb#260]
Hi,
iobroker.Admin: 5.4.9
iobroker.influxdb: 3.0.2

Boolean Werte werden in der Admin-GUI-influxdb als "null" angezeigt, entsprechend auch nicht als Grafik.
Mit eingeschaltetem Debug ergibt sich eine eigentlich korrekt erscheinende Behandlung der Werte, hier Übergang von false auf true:

influxdb.0 | 2022-05-16 17:39:19.656 | debug | Datatype hm-rega.0.2957: Currently: boolean, StorageType: Boolean
influxdb.0 | 2022-05-16 17:39:19.654 | debug | Value logged hm-rega.0.2957, value=true, ts=1652715558647
influxdb.0 | 2022-05-16 17:39:18.653 | debug | Min-Delta ignored because no number hm-rega.0.2957, last-value=false, new-value=true, ts=1652715558647
influxdb.0 | 2022-05-16 17:39:18.651 | debug | new value received for hm-rega.0.2957 (storageType Boolean), new-value=true, ts=1652715558647, relog=false

In der Objektanzeige des Admin-GUI werden die Werte und ihre Änderung korrekt als "true" und "false" ausgegeben, aber eben nicht innerhalb der Werteanzeige des influxdb Adapters.

cu
Harvey

Der Wert hm-rega.2957 als "false"
![Image 001](https://user-images.githubusercontent.com/10156426/168638649-47f179e7-a3f3-43b2-a790-bd948a924d14.png)
Der Wert und seine Ausgabe im Influxdb-Adapter, die diversen Werte kommen von Änderungen, sind also zeitlich richtig und auch echte Änderungen, aber leider wird halt nicht "true" oder "false" angezeigt :-(
![Image 002](https://user-images.githubusercontent.com/10156426/168638674-d5105da7-a088-4989-b24b-c4554b32622a.png)

**Comment by Apollon77** [comment]
Can you please try with JavaScript to do a "getHistory" call to see if the data come back correctly as boolean? Because if yes then it would be an admin issue

**Comment by harvey637** [comment]
Moin, Appollon77,
looks that you are right:

```
...
hm-rega.0.295716527726238760.4304733531109908  Response rows:  [[{"time":"2022-05-15T22:00:56.221Z","value":false}],[{"time":"2022-05-16T08:08:19.147Z","value":false},{"time":"2022-05-16T08:42:09.65Z","value":false},{"time":"2022-05-16T08:44:49Z","value":false},{"time":"2022-05-16T10:47:11.296Z","value":true},{"time":"2022-05-16T14:32:11.406Z","value":true},{"time":"2022-05-16T14:41:41.397Z","value":false},{"time":"2022-05-16T14:41:56.185Z","value":false},{"time":"2022-05-16T14:42:45.185Z","value":true},{"time":"2022-05-16T14:42:58.032Z","value":true},{"time":"2022-05-16T14:44:30.042Z","value":true},
...
```

so I will reask in Admin (and possible echarts)
Thank You!
Harvey

**Comment by Apollon77** [comment]
No.,

**Comment by Apollon77** [comment]
it is an issue in adapter. I already found it. If you like: Try GitHub version. Restart adater manually afterwards

**Comment by harvey637** [comment]
Hi Apollon77,
not familiar with putting the new main.js into an running system - what do I do? (running ssh on the system is ok)

If it is downloadable somehow I can test.
Thankyou for your quick response (and I will close the issue in the admin project :-)
cu
Harvey

**Comment by Apollon77** [comment]
Admin - enable expert mode - CUstom install (Github) icon - choose middle tab "From GitHub" - select influxdb - hit install

**Comment by Apollon77** [comment]
I verified it on my test system. will release update later

**Comment by harvey637** [comment]
confirmed to work, thank you! (pls close after released update)
Harvey

**Comment by Apollon77** [comment]
3.1.0
