### ISSUE TITLE
InfluxDB 2: Datenpunkte im Verlauf (Admin) bearbeiten/löschen/updaten ...

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.influxdb#262]
Bei Verwendung von InfluxDB 2 können im Admin keine aufgezeichneten Werte im Verlauf geändert oder gelöscht werden. Es wäre schön, wenn dies analog zu InfluxDB 1 angeboten würde.

Vielen Dank!

**Comment by Dettenrocks** [comment]
Wird diese Funktion noch nachgereicht bzw wird hier noch dran gearbeitet? Auch im Bezug das die aus JavaScript genutzt werden kann?

**Comment by Apollon77** [comment]
Naja das Issue ist als Enhancement offen, also ist es mal nicht "nicht geplant", sonst wäre es geschlossen :-)

Es hat aber bisher noch niemand Zeit gehabt das zu tun. Auch ist Löschen von Datensätzen in der InfluxDB 2 nicht ganz so einfach ...

**Comment by Marc-Berg** [comment]
Ich habe die "Löschen" Funktion für InfluxDB 2.x mal fix umgesetzt, da mich das Löschen auf Kommandozeile genervt hat. Das funktioniert, soweit ich das testen konnte. Aufgrund meiner beschränkten Javascript Programmierkenntnisse müsste da mal jemand SEHR kritisch drüber schauen. In Summe sind es etwa 35 Zeilen Code.

[DatabaseInfluxDB2x.js.txt](https://github.com/ioBroker/ioBroker.influxdb/files/11575810/DatabaseInfluxDB2x.js.txt)
[main.js.txt](https://github.com/ioBroker/ioBroker.influxdb/files/11575811/main.js.txt)

**Comment by harvey637** [comment]
Hi,
ich habe gesehen, dass diese Funktion im Expertenmodus vorhanden ist, sehr schön! (habe nur minimal getestet). Damit habe ich etwa einen fehlerhaften Ausreisser korrigiert (aber noch keine einzelne Datenpunkte entfernt).

Eine kleine Verbesserung könnte noch sein, beim Abwählen des (früheren) Speicherns (also "Aktiviert -> MIT Haken zu "Akiviert" -> kein Haken) das komplette Löschen des Datenpunktes direkt anzubieten (ohne Expertenmodus, mit Sicherheitsabfrage ".... werden alle Datenpunkte dauerhaft komplett gelöscht..."

Aber was mache ich, wenn der Datenpunkt nicht mehr existiert, z.B. weil die Variable in homematic gelöscht wurde, obwohl sie vorher in influx gespeichert wurde?
Und wie finde ich diese Leichen, z.B. über letzter Dateneintrag "sehr alt"? Alternativ gerne CLI Beispiele, auch wenn die Kommandozeile nicht optimal für Endanwender aussieht.

Vielen Dank
cu
Harvey

**Comment by Marc-Berg** [comment]
> Eine kleine Verbesserung könnte noch sein, beim Abwählen des (früheren) Speicherns (also "Aktiviert -> MIT Haken zu "Akiviert" -> kein Haken) das komplette Löschen des Datenpunktes direkt anzubieten (ohne Expertenmodus, mit Sicherheitsabfrage ".... werden alle Datenpunkte dauerhaft komplett gelöscht..."

Da kann ich dir nicht folgen. Was ist mit "Abwählen des früherens Speicherns" gemeint? Wenn es eine neue Funktion ist, mach doch bitte einen Feature Request auf. Mein Ziel ist zunächst, die vorhandenen Funktionen aus der InfluxDB 1.x nachzubauen.

Aber danke für's Testen!

**Comment by harvey637** [comment]
Hi Marc-Berg,

danke für die schnelle Nachfrage:

Ich meine damit, dass ein Datenpunkt schon mal fürs speichern in influxdb vorgesehen war. Also das "Zahnrad" der Datenpunktes gewählt war, und dann das Speichern "Aktiviert" worden ist. Jetzt landen also Datenwerte in der Datenbank, entsprechend der Vorgaben z.B. "nur die Änderungen".

Wenn dieser Datenpunkt etwa "Unsinn" war und gelöscht werden soll können 2 Dinge passieren: 
1) Ich lösche mit Hilfe Deiner Funktionserweiterung im Tab "Verlaufsdaten" mit dem Mülleimersymbol die Daten. (Wichtig DIES zuerst zu machen!) Dann setzte ich das Influxdb-Speichern auf "Aktiviert = NO (kein Haken mehr). Erst danach lösche ich die Variable in Homematic und restarte in iobroker den hm.rega Adapter durch. Dann ist der Datenpunkt auch weg.
2) Ich lösche dummerweise die Variable in Homematic zuerst. Wenn ich schnell bin kann ich wie oben noch den Datenpunkt aus der influxdb löschen. Wenn ich zu langsam bin bzw. hm.rega neu gestartet wird ist der Datenpunkt weg. Damit habe ich auch kein Handle mehr um wie in 1) die Daten aus der Datenbank zu löschen, also kein Zahnrad mehr hinter dem ja nicht mehr vorhandenen Datenpunkt :-(

Mein Feature-Request beinhaltet also als erstes, dass beim DE-Aktivieren der Influxdb-Speicherung eines vorhandenen Datenpunktes zusätzlich angefragt wird, ob ich etwa die Datenpunkte dauerhaft komplett aus der Influxdb löschen möchte. Wenn ja (mit Sicherheitsabfrage) sind sie halt weg, sonst bleiben sie erhalten und die historischen Daten können etwa in historischen Charts noch verwendet werden. 
Als weiteres könnte ich mir bei einem Leben auf einem Ponyhof vorstellen, dass es in der Influxdb Verwaltung eine Funktion geben könnte um nach den versehentlich Löschen von Datenpunkten nachträglich diese Datenpunkte komplett aus der DB zu löschen. Das ist sicherlich eher komplex in einer GUI darzustellen, also was für die ferne Zukunft vielleicht.
Über CLI muss ich mal nachdenken bzw nachlesen....
Sowas wie "welcher Datenpunkt" wurde am längsten nicht mehr aktualisiert?" Komplexer ist dann die Funktion, alle Datenpunkte zu finden, für die es in hm.rpc und hm.rega keine Datenpunkte mehr gibt....

Dir noch ein schönes Wochenende
cu
Harvey

**Comment by Marc-Berg** [comment]
Ah, ja jetzt vestehe ich deinen Punkt. Ja, da kann ich mir auch noch ein paar Ergänzungen vorstellen, die ganz nett wären. Aber das meiste bekommt man mit der CLI hin, wenn du das einmal gemacht hast, sollte das gehen. Mit dieser Anfrage bekommst du übrigens alle Measurements angezeigt, sortiert nach dem Measurement mit dem ältesten (letzten) Eintrag.
```
 from(bucket: "iobroker")
  |> range(start: 0)
  |> keep(columns: ["_time","_measurement"])
  |> last(column: "_time")
  |> group()
  |> sort(columns: ["_time"], desc: false)
```

**Comment by Marc-Berg** [comment]
Kann geschlossen werden. https://github.com/ioBroker/ioBroker.influxdb/pull/332
