### ISSUE TITLE
Link entweder auf Admin oder Grafana

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.influxdb#27]
Hallo,
bei der Instanze Ansicht des Adapters sollte es einen Link auf Grafana http://:3000  oder auf die Adminseite von Influxdb http://:8083 geben.

**Comment by Apollon77** [comment]
hm ... Grafana hat nicht jeder und Admin-Interface kann man auch abschalten und ist sogar offiziell "deprecated" ... Von daher würde ich beides nicht machen wollen
