### ISSUE TITLE
deleteRange geht nicht ->  Invalid call

### ISSUE THREAD

**Issue by hliebscher** [ioBroker/ioBroker.influxdb#270]
die option deleteRange funktioniert leider nicht
alle anderen delete und deleteAll funktioniert

 javascript.0 (594) script.js.common.Venus.test: Invalid call: {"command":"deleteRange","message":{"id":"valloxmv.0.ACTIVE_PROFILE","start":1653955200000,"end":1654171098519},"from":"system.adapter.javascript.0","callback":{"message":

Adatper version
v3.1.3

**Comment by Apollon77** [comment]
Yes, the call is invalid for your usecase.

Refer to readme please:

```
sendTo('influxdb.0', 'deleteRange', [
    {id: 'mbus.0.counter.xxx', start: '2019-01-01T00:00:00.000Z', end: '2019-12-31T23:59:59.999'}, 
    {id: 'mbus.0.counter.yyy', start: 1589458809352, end: 1589458809353}
], result => console.log('deleted'));

```

YOu need to send the array even if only with one element

**Comment by hliebscher** [comment]
sorry my mistake it works fine ;-)
