### ISSUE TITLE
Adapter not working with influx 1.x

### ISSUE THREAD

**Issue by m-rohlfs** [ioBroker/ioBroker.influxdb#280]
Adapter is starting, but get error : 

<html><body>

influxdb.0 | 2022-07-15 18:37:34.187 | error | main/getObjectView: Error: Cannot find search "custom" in "system"
-- | -- | -- | --
influxdb.0 | 2022-07-15 18:37:34.164 | error | Cannot find search "custom" in "system"

</body>
</html>

databse is created but no data ist writeen an no datapoints are createtd

**Comment by Apollon77** [comment]
Which js.controller do you use?

Please try to run "iob setup first" ... still happening afterwards?
