### ISSUE TITLE
Unable to storeState with value "null"

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.influxdb#282]
**Describe the bug**  

```javascript
const state = {
    "id": "0_userdata.0.test.myNumber",
    "state": [
        {
            "val": null,
            "ts": 1636560206510,
            "ack": true,
            "q": 64
        }
    ]
};
sendTo('influxdb.0', 'storeState', state, (result) => {
    console.log(JSON.stringify(result));
});
```

Result:

```json
{
    "error": "1 errors happened while storing data",
    "errors": [
        "Error writing state for 0_userdata.0.test.myNumber: undefined, Data: {\"val\":null,\"ts\":1636560206510,\"ack\":true,\"q\":64}"
    ],
    "successCount": 0
}
```

Are null values not allowed in InfluxDB?

*Happend during history db migration - script stopped due to errors*

**Expected behavior**  

Null value is written to DB (if not configured to avoid that).

**Versions:**  
 - Adapter version: 3.1.7
 - InfluxDB 2.3

**Comment by Apollon77** [comment]
> Are null values not allowed in InfluxDB?

Exactly :-) RTFM ;-)) https://github.com/ioBroker/ioBroker.influxdb#influxdb-and-data-types

**Comment by Apollon77** [comment]
PS: I remember i should have added a check in the history/migration script? hhmmm.... maybe we silently ignored such errors before but now no longer ... could be ... there were many changes in the katest majotr version

**Comment by klein0r** [comment]
Thank you! In that case I will update the migration script to work with the latest versions again.

**Comment by Apollon77** [comment]
Thank you very much!
