### ISSUE TITLE
Einträge löschen/Datenpunkte neu anlegen

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.influxdb#283]
Aufgrund meines vorher gemeldeten Fehlers und den damit verbunden historischen Problem (scheinbar) (https://github.com/ioBroker/ioBroker.influxdb/issues/281)
wäre es ja toll wenn es eine Möglichkeit gäbe die gespeicherten Daten eines Datenpunktes zu löschen damit eine neue, richtige Anlegung und Speicherung möglich ist.

aber ich möchte ja nicht ALLE Daten Löschen sondern nur von einem Datenpunkt oder einem Adapter oder so.
Im Moment ist das verhalten so das er dann einfach nicht mehr loggt aber nicht löscht.

**Comment by Apollon77** [comment]
Geht für v1, v2 fehlt noch

**Comment by Apollon77** [comment]
duplicate #262
