### ISSUE TITLE
"Minimale Differenz zum letzten Wert" loggt zu oft / doppelt

### ISSUE THREAD

**Issue by tseroo** [ioBroker/ioBroker.influxdb#286]
Es werden Daten geschrieben, die die minimale Differenz unterschreiten. Einstellung am Alias-DP ist 0.1, und hier die Werte im Bucket:
![image](https://user-images.githubusercontent.com/10330889/183573919-152f8282-b60f-430a-b440-0a777d0d8412.png)

Im debug-mode steht dann folgendes:
![image](https://user-images.githubusercontent.com/10330889/183574110-fd35e2e0-5fff-41cc-b97b-63b411832bc6.png)

Er wartet immer brav, bis der Wert überschritten ist, aber dann schreibt er gleich 2x in die InfluxDB und die Werte liegen natürlich zu eng beieinander ...

InfluxDB: 2.3.0
Adapter: 3.1.7

**Comment by Apollon77** [comment]
Dann bitte die EInstellungen prüfen. Ich vermute es ist aktiviert das extra werte zur bessseren grafischen darstellung geschrieben werden. Schalte dasd aus und die zusatz werte verschwinden.

Mehr Infos unter https://forum.iobroker.net/topic/54834/influxdb-3-0-0-verf%C3%BCgbar-eine-zusammenfassung

**Comment by tseroo** [comment]
Ah ja, hast eh schön beschrieben. Hab's nur überlesen, weil ich mir dachte,
das kann nix damit zu tun haben.
Denn 3 Minuten wird gar nichts geschrieben und dann aber innerhalb von nur
3 sek gleich 2 Werte ... das verbessert die grafische Darstellung IMHO
nicht sonderlich, deswegen bin ich gar nicht auf die Idee gekommen, dass
das was damit zu tun haben könnte.

Aber jetzt haut's so hin, wie ich mir das vorstelle! Danke für den Adapter!
Echt cooles Teil!

LG



Am Di., 9. Aug. 2022 um 10:05 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
In deinem Speziellen Fall mag das nicht so viel bringen, aber der generelle Purpose ist immer noch valide :-)

Man hat regeln die bestimmte Werte (warum auch immer) auslassen. Dann plötzlich, sagen wir mal, nach 2h wird ein neuer wert geloggt.
Eine Charting Software kann dann nur das entweder als Treppe darstellen (was formal falsch ist) oder als "durchgezogende ansteigende/abfallende Linie", was ggf auch falsch ist.

Den "zuletzt verworfenen wert" zusätzlich zu loggen bringt einen weitere Datenpunkt und könnte so die grafische darstellung verbessern.

Wie gesagt in deinem Fall grenzwertig vom Nutzen her
