### ISSUE TITLE
Retention policy is global and only set once on db-creation

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.influxdb#29]
Currently the set Retention Policy is only set once when the DB is created with the value from the adapter config.
Any change afterwards has no effect
Any changeon datapoint level has no effect

Reason: Everything is handled by DB and only one retention policy is created on db creation ...

Solution would be to check if we can create all possible retention policies and then use that policy also when writing the values. The adapter-set retention policy will be set as default (which is in the end unimportant)

**Comment by hacki11** [comment]
I did recognize today that all my data is just cut by the one year default retention policy of influxdb. As you said all custom retention policy configured for each datapoint has no effect. unfortunately i do not have a backup from a year ago. do you know if there is any change within influxdb to recover them?

**Comment by Apollon77** [comment]
If you have no backup from your inflxdb data then, sorry but I do not know anything

**Comment by stenmic** [comment]
Will there be an update? 
Can I change the value for "global" in influx manually by this way? 
(The values should never be deleted )
`ALTER RETENTION POLICY "global" ON "iobroker" DURATION **0s** SHARD DURATION 24d DEFAULT `

**Comment by Apollon77** [comment]
Solbinfg this is not thaaat easy ... I think we will need to take care once we start adjisting the adapter for influxdb 2 ...

In fact you can change the retention policy on server side anytime. It currently is only created once when the DB is created and not touched later

**Comment by stenmic** [comment]
OK, but would that be the right command to avoid erasing any data after 1 Year?
I'm not sure about "DURATION 0s"

**Comment by Apollon77** [comment]
honestly ... no idea right out of my head, you need to check influxdb docs (or me too)

**Comment by grdminer** [comment]
@stenmic assuming you are using standard you can show the available retention policies on influx CLI with `show retention policies on "iobroker"`.  You can open the CLI simply by typing command `influx` on command line.

It should state something like:

```
name    duration shardGroupDuration replicaN default

autogen 0s       168h0m0s           1        false
global  8760h    168h0m0s           1        true
```

The policy named global should be the one created by the adapter and its duration is 8760h = 1 year and its the default policy. To avoid deletion of data the easiest way is to use command `ALTER RETENTION POLICY "global" on "iobroker" DURATION 0s
`. Its setting the duration to 0s so no deletion at all. BTW: Deleting the policy deletes all data related to it!

please check for details **before** trying: [https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#retention-policy-management](url)

**Comment by Excodibur** [comment]
Fix will be delivered as part of InfluxDB Adapter 2.0.0 (and subsequent releases).
