### ISSUE TITLE
Messwerte in influxdb über Adapter löschen

### ISSUE THREAD

**Issue by DominikWild** [ioBroker/ioBroker.influxdb#297]
Hallo zusammen,

habe gelesen, dass das Löschen von einzelnen Messwerten über den Adapter möglich sein soll:
![image](https://user-images.githubusercontent.com/56350658/193537005-5560f960-bb74-4d97-b988-ef2a384ea63f.png)

Habe auf meinem ioBroker den aktuellen influxdb (V3.1.8) installiert und sehe die Option nicht. Ich nutze Influx CLI 2.4.0.

![image](https://user-images.githubusercontent.com/56350658/193537741-1d5155bd-d562-488b-bb2f-8b9ebda8b17f.png)

**Comment by Apollon77** [comment]
duplicate #262
