### ISSUE TITLE
Auswahl der Retention Time bzw. des Buckets

### ISSUE THREAD

**Issue by Tagiwara** [ioBroker/ioBroker.influxdb#319]
Hallo,

wenn ich Daten aus IoBroker logge und diese permanent aufbewahrt werden sollen, dann lasse ich diese in ein Bucket (iobroker_permanent) schreiben, wo ich eine umbegrenzte Retention Time habe... also in der InfluxDB "Never" ausgewählt habe.

Wenn ich jetzt zusätzlich noch Daten loggen möchte, die bspw. nur 30 Tage aufbewahrt werden sollen, dann müsste ich hierfür ja eine zweite Influx Instanz anlegen und hier ein temporäres Bucket (iobroker_temp) eintragen.

2 Buckets zu haben für IoBroker ist ja nicht schlimm, aber extra eine zweite Instanz finde ich etwas unpraktikabel.

Wäre es möglich, dass man bei den Einstellungen im Datenpunkt welcher geloggt werden soll, noch das entsprechende Bucket eintragen kann?

**Comment by Apollon77** [comment]
Sorry, nein, das ganze mit retention und das synchron zu halten ist schon komplex genug ... Die paar MB zusätzlich RAM für eine zweite Instanz und dann bei der konfiguration sauber zuweiesen was wo hin geht ist hier dann der klar einfachere Weg  (weil ob du es jetzt in der Konfig einstellst oder ... inder Konfig "ein bissl anders) einstellst sollte egal sein.
