### ISSUE TITLE
Naming restriction for the Influx token's name?

### ISSUE THREAD

**Issue by Pedder007** [ioBroker/ioBroker.influxdb#325]
**Describe the bug**  
When first time setting up and connecting Influx for iobroker, I failed multiple times to connect the adapter to the Influx instance. Changed and tested new credentials multiple times but always got a 'http authorization failure'. In the end I generated a complete new token in Influx by completely deleting the former one. When doing it this time, I also changed the name of the token from 'iobroker@influx' to something without an '@' in the name.
After that the adapter directly connected to the data base, which I wondered about, as the name of the token is not used in one of the config fields in the adapter.
Thus I would like to make this transparent here, maybe to check also by others.
 
**To Reproduce**  
To be quiet open, I didn't switch it back yet (incl. an '@' in the Token's name), as I was happy in the end, that it works now ;-)

**Expected behavior**  
Accept in the future also '@' in the config or put a respective hint into the adapter docu.

**Screenshots & Logfiles**  
-

**Versions:**  
All ioBroker related on the newest status on the Master.
Same also in the Proxmox environment, where Influx and also the repsective iobroker Slave, incl. the adapter, runs.

**Additional context**  
-

**Comment by Marc-Berg** [comment]
I can't reproduce the error. What do you mean when you say "token name"? I can only assign a description when creating the token. I have tested this now with "@" in the username as well as in the token description. Both works.

![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/99531337/0e03a2dc-322b-4c55-aab9-64b97a46241f)
