### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by poldiderjungdrache** [ioBroker/ioBroker.influxdb#331]
![IMG_0318](https://github.com/ioBroker/ioBroker.influxdb/assets/59320185/e7fedb88-2246-453b-bfa2-23d33feb9a97)
Hello,
I am getting ‘Error: self signed certificate in certificate chain‘ message when testing the DB connection to my influx 2.0.
To my understanding he should just ignore the self signed cert as I don’t tell him to ‘Vaildate SSL certificate’. So how come this error pops up?
Full explanation I have an internal CA that has signed the cert. The full chain is added to influx. So my understanding is he does not like the rootCA, which of course is not trusted. But then again why does he even care if I tell him not to?
I’ve also tried to add my rootCA to the trust store of the OS (raspbian). 
curl is happy with the cert presented:

```
pi@iobroker-master:~ $ curl https://influx.tianmimi.infra:18086
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="InfluxDB is a time series platform, purpose-built by InfluxData for storing metrics and events, provides real-time visibility into stacks, sensors, and systems."><title>InfluxDB</title><base href="/"><link rel="shortcut icon" href="/favicon.ico"></head><body><div id="react-root" data-basepath=""></div><script src="/4ba86f89e6.js"></script></body></html>
```

**To Reproduce**  
1. Go to adapter config
2. Set up connection to influxDB using HTTPs (DB should be set up with self signed cert or chain of trust with an untrusted RootCA), don’t set ‘Validate SSL certificate’
3. Push ‘Test connection’
4. recieve error

**Expected behavior**  

**Screenshots & Logfiles**  
added

**Versions:**  
 - Adapter version: 3.2.0
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: Raspbian

**Comment by Apollon77** [comment]
Is the error only happening in "test connection"? Does adapter work if you safe it or do you get te same error?

**Comment by Apollon77** [comment]
Ok, so I assume that the "ignore ssl cert" flag is not transported correctly when checking connection, ok, thx. Will look at it

**Comment by Marc-Berg** [comment]
The issue can be closed. https://github.com/ioBroker/ioBroker.influxdb/pull/337
