### ISSUE TITLE
storeState example 2. not working

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.influxdb#335]
Hallo,

PI4 (latest)
node v18.16.0
influx2.7x

-one ID and array of state objects

hat nicht funktioniert. folgendes state obj hatte ich erstellt und angehangen: 
ts ist eine zukünftiger Zeitpunkt

`[{"ts":1686366000000,"val":0,"from":"custom.script","ack":true},{"ts":1686369600000,"val":98,"from":"custom.script","ack":true},{"ts":1686373200000,"val":1142,"from":"custom.script","ack":true},{"ts":1686376800000,"val":2558,"from":"custom.script","ack":true},{"ts":1686380400000,"val":4353,"from":"custom.script","ack":true},{"ts":1686384000000,"val":5851,"from":"custom.script","ack":true},{"ts":1686387600000,"val":6944,"from":"custom.script","ack":true},{"ts":1686391200000,"val":7575,"from":"custom.script","ack":true},{"ts":1686394800000,"val":7753,"from":"custom.script","ack":true},{"ts":1686398400000,"val":7496,"from":"custom.script","ack":true},{"ts":1686402000000,"val":6832,"from":"custom.script","ack":true},{"ts":1686405600000,"val":5770,"from":"custom.script","ack":true},{"ts":1686409200000,"val":4354,"from":"custom.script","ack":true},{"ts":1686412800000,"val":2845,"from":"custom.script","ack":true},{"ts":1686416400000,"val":1589,"from":"custom.script","ack":true},{"ts":1686420000000,"val":731,"from":"custom.script","ack":true},{"ts":1686423600000,"val":155,"from":"custom.script","ack":true}]`
Rückgabe von senTo:
` {'success':true,'successCount':1,'connected':true,'seriesBufferCounter':406,'seriesBufferFlushPlanned':false}`

Nach dem ich sie einzeln per sendTo geschickt  habe (anstatt sie erst in einem array zu parken), sind sie in der Datenbank angekommen.

**Comment by Apollon77** [comment]
Wie sieht die vollständige message aus?

**Comment by ticaki** [comment]
Verstehe die Frage nicht. Dort oben ist die komplette Rückgabe von sendto. Der Aufruf sah so aus.
`
sendTo('influxdb.1', 'storeState', [{
  id: '0_userdata.0.Dummys.SolForcast_helper',
  state: state
}], function(result){log(result)});
`

**Comment by Marc-Berg** [comment]
Du rufst die Funktion falsch auf.

Falsch: 
`sendTo('influxdb.1', 'storeState', [{ id: '0_userdata.0.Dummys.SolForcast_helper', state: state }], function(result){log(result)});`

Richtig:

`sendTo('influxdb.1', 'storeState', {id: '0_userdata.0.Dummys.SolForcast_helper',state: state}, function(result){log(result)});`

**Comment by ticaki** [comment]
Recht hast du, sry bin ich wohl mit den Beispielen durcheinander gekommen sry.
