### ISSUE TITLE
[Enhancement] Store password encrypted 

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.influxdb#35]
Was mentioned in https://github.com/jensweigele/ioBroker.yahka/issues/53#issuecomment-442756328

**Comment by Apollon77** [comment]
yes :-(

**Comment by Excodibur** [comment]
Todo: Change implementation to use _encryptedNative_ and _protectedNative_ (see doc https://github.com/ioBroker/ioBroker.js-controller) for **password** and **token**.
