### ISSUE TITLE
Im Influx Adapter lässt sich Token nicht speichern 

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.influxdb#353]
Hallo 
unter dem Influx Adapter lässt sich nach Eingabe des Token dieser nicht speichern. 
influxdb.0v3.2.0

  | PID | Zeit |   | Nachricht
-- | -- | -- | -- | --
influxdb.0 | 1041876 | 2023-08-29 21:21:42.270 | error | HttpError: unauthorized access
influxdb.0 | 1041876 | 2023-08-29 21:21:32.264 | error | HttpError: unauthorized access
influxdb.0 | 1041876 | 2023-08-29 21:21:22.256 | error | HttpError: unauthorized access
influxdb.0 | 1041876 | 2023-08-29 21:21:12.248 | error | HttpError: unauthorized access
influxdb.0 | 1041876 | 2023-08-29 21:21:02.237 | error | HttpError: unauthorized access
influxdb.0 | 1041876 | 2023-08-29 21:20:52.222 | error | HttpError: unauthorized access

PID

Zeit

	
Nachricht

influxdb.0
[1041876](tel:1041876)	2023-08-29 21:21:42.270	error	HttpError: unauthorized access

influxdb.0
[1041876](tel:1041876)	2023-08-29 21:21:32.264	error	HttpError: unauthorized access

influxdb.0
[1041876](tel:1041876)	2023-08-29 21:21:22.256	error	HttpError: unauthorized access

influxdb.0
[1041876](tel:1041876)	2023-08-29 21:21:12.248	error	HttpError: unauthorized access

influxdb.0
[1041876](tel:1041876)	2023-08-29 21:21:02.237	error	HttpError: unauthorized access

influxdb.0
[1041876](tel:1041876)	2023-08-29 21:20:52.222	error	HttpError: unauthorized access

Debian Bullseye 11

ioBroker.admin v6.9.1

Node.js: v18.17.1

NPM: 9.6.7

js-controller

JS controller Installiert neu: 5.0.12

OS: linux

Latest

**Comment by Apollon77** [comment]
The infos in the readme regarding the needed rights for the used token are considered?

**Comment by JogiBarbarski** [comment]
Sorry, verstehe ich nicht. Im Browser bei Influx einen Token erstellt, den kopiert, im Influx Adapter eingetragen und bei Grafana eingetragen. 
Im IoBroker, Influxdb0 Adapter da lässt er sich nicht änder oder schleichen. Die Seite ist dann wie eingefroren.

**Comment by Apollon77** [comment]
see requirements for the token here https://github.com/ioBroker/ioBroker.influxdb#influxdb-2x
