### ISSUE TITLE
Schaltflächen in Standardeinstellungen

### ISSUE THREAD

**Issue by Klaus-Lucas** [ioBroker/ioBroker.influxdb#356]
Habe eine weitere Instanz des Adapters (1) installiert und dabei bei den Standardeintellungen **Storage Vorhaltezeit** das folgende Verhalten festgestellt:
Ich ändere etwas auf der Seite z.B. **Optimierte Protokollierung** und wähle dann aus dem Klappmenü einen anderen Wert aus, so werden die unter Schaldflächen **Speichern**,  **Speichen und Schliessen** und **Schliessen** rot umrandet und die beiden ersten werden zudem noch ausgegraut und damit nicht mehr anwählbar. Stelle ich die Vorhaltezeit auf den alten Wert zurück, erscheinen die Schaltflächen wieder.

1) Ausgangslage mit selektierter **Optimierte Protokollierung**. Da es eine Änderung ist, werden die beiden Schaltflächen  **Speichern**,  **Speichen und Schliessen** auswählbar:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/0a381081-796a-4cfa-a39f-73c57f598364)

Andere Zeit gewählt:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/428ddf7d-2900-4f15-9f94-4e2bdea2da36)

Dies in einem 3 Sek. Video:
https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/0022ce97-9f6d-4487-ae03-92f3107495f1

und wieder zurück auf die ursprüngliche Zeit:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/62a7494e-d8ae-43e1-9c09-3e6fe41a2eb0)

2) Zustand nach dem Öffnen:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/f1205ab3-7a64-48b7-8715-05b348f72753)

Zeit ändern. **Speichern**,  **Speichen und Schliessen** werden ganz kurz Weiß, weil die Änderung erkannt wurde und dann wie abgebildet:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/ba28ba5e-7eea-4765-8482-ec3c6499fd22)

und wieder zurück auf die ursprümgliche Zeit:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/dc97d7b2-9ef2-46dd-ae81-f34c40936816)

3) Bei der Instanz 0, die ich bisher noch nie gestartet habe, verhält sich das noch ein bisschen anders:

Ausgangslage:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/2ac070d9-fe62-4ad4-80fa-90695f7aaa75)

Änderung der Zeit von 1. Jahr auf 2. Jahre bzw. keine autom. Löschung -> OK
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/8ec4386c-4220-4805-a288-73f391f9cd48)

Wähle ich eine Zeit kleiner als 1 Jahr (6 Monate,...) tritt das Verhalten wieder auf:
![grafik](https://github.com/ioBroker/ioBroker.influxdb/assets/36620907/2dae3c73-76af-4e77-a8db-1c081be44de5)

Ggf. ein Admin Problem?
Bei meinen anderen InfluxDB-Instanzen (2-5) tritt das Problem nicht auf. Die sind vor der neuen Admin-Version installiert und gestartet worden.

**Versions:**  
 - Admin: 6.10.2 & 6.10.4
 - Adapter version: 3.2.0
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: Ubuntu 22.04.3 LTS
 - Firefox 117.0.1 x64

**Comment by Marc-Berg** [comment]
Ich verstehe das Problem (noch) nicht. Das Verhalten ist doch genau wie gewüscht, wenn man die Vorhaltezeit verkürzt, können potentiell Daten verloren gehen. Deshalb muss man erst die Checkbox "Geringere Vorhaltezeit anwenden" aktivieren, damit die Speichern-Buttons aktiv werden. Vorher erscheint noch ein deutlicher Warnhinweis.

**Comment by Klaus-Lucas** [comment]
Hallo Marc,
da war ich wohl blind und habe den roten Text nicht wahrgenommen.
Danke für den Hinweis.

**Comment by Klaus-Lucas** [comment]
und bitte schließen
