### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by quotschmacher** [ioBroker/ioBroker.influxdb#359]
**Describe the bug**  
I open the "Instanzeinstellungen" for the influx adapter, the buttons for applying the changes are greyed out:

![Screenshot 2023-10-17 094841](https://github.com/ioBroker/ioBroker.influxdb/assets/50583947/167df9f7-c882-483e-bcd9-dd6abccabcb8)

I edit some values and the buttons become grey:

![Screenshot 2023-10-17 094549](https://github.com/ioBroker/ioBroker.influxdb/assets/50583947/e54c8e83-1e4c-4bea-af31-7557b4c13957)

If i change something on any other adapter, the buttons become blue:

![Screenshot 2023-10-17 094515](https://github.com/ioBroker/ioBroker.influxdb/assets/50583947/31b7204b-8c90-4a77-bc44-7d127ce35c53)

As they are grey I am not able to save my settings. Only closing the dialog with nothing saved works.

Already tried to uninstall the adapter and install it with another instance number, but it does not work.

**Versions:**  
 - Adapter version: v3.2.0
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: Docker / Linux

**Comment by quotschmacher** [comment]
Update: after the 10th removal and new installation of the adapter, the settings are saved. but the buttons do not change to blue like they do on other adapter's setting pages.

**Comment by Marc-Berg** [comment]
With many adapters, the "Save" buttons become grey, e.g. with the "Admin" adapter. This is not a bug. I cannot understand the other behaviour. I can save when the buttons are grey.

**Comment by Marc-Berg** [comment]
@quotschmacher Can this issue be closed?

**Comment by quotschmacher** [comment]
@Marc-Berg as it cannot be reproduced and somehow worked for me lateron i would say it can be closed.
