### ISSUE TITLE
Token can not saved - TypeError window.CryptoJS

### ISSUE THREAD

**Issue by heni1** [ioBroker/ioBroker.influxdb#369]
**Describe the bug**  
The configuration can no longer be saved as soon as a character is written in the "Token" field. The error message appears: `[JsonConfig] Cannot set object: TypeError: window.CryptoJS is undefined`

**To Reproduce**  
1. Installing the adapter
2. Filling in the token field
3. press save button

**Expected behavior**  
Saving the token and establishing a
 connection to the Influx DB

**Screenshots & Logfiles**  
![InfluxAdapterError](https://github.com/ioBroker/ioBroker.influxdb/assets/3791048/75c16eb1-f754-4fd9-98ea-519429e065d6)

**Versions:**  
 - Adapter version: 3.2.0
 - JS-Controller version: 5.0.17
 - Node version: v18.19.0
 - Operating system: Synology Docker buanet/iobroker

**Additional context**  
if a old config saved, the configarion form can not be loaded. The same problem was by a old version of JS-Controller V4...

**Comment by Apollon77** [comment]
Whoch browser do you use? Did you tried another browser?

**Comment by Apollon77** [comment]
Should be fixed by Admin 6.13.11
