### ISSUE TITLE
HttpError: runtime error @4:12-4:122: filter: type conflict: bool != string

### ISSUE THREAD

**Issue by tipp88** [ioBroker/ioBroker.influxdb#372]
History for states of type String are not shown. A type conflict error is thrown.

![image](https://github.com/ioBroker/ioBroker.influxdb/assets/68737433/aae147ec-1818-4604-b6f3-1348795c2a79)

![image](https://github.com/ioBroker/ioBroker.influxdb/assets/68737433/5f9674f2-c869-4bfc-9445-a46e17616933)

![image](https://github.com/ioBroker/ioBroker.influxdb/assets/68737433/5d49439b-9ce0-4000-b154-5ce412ce553f)

**Comment by Apollon77** [comment]
The error means that there seems to be a value in the DB which is NOT a string, but a boolean and so selection do not work ... 

Else pleas eenable debug log for the adapter AND turn on enhanced logging for this datapoint in the config and post a debug log from such a query ... Then we maybe can look at the reasons for the error

**Comment by Marc-Berg** [comment]
The adapter tries to find out whether the data type is "boolean" by checking whether at least one content is "true" or "false". 
This query is incorrect, a filter is missing here.

Incorrect:
```
from(bucket: "iobroker") 
 |> range(start: 1999-12-31T23:00:00.000Z, stop: 2025-12-01T14:31:44.004Z)
 |> filter(fn: (r) => r["_measurement"] == "0_userdata.0.example2" and contains(value: r._value, set: [false, true])) 
 |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
 |> group()
```

Correct:
```
from(bucket: "iobroker") 
 |> range(start: 1999-12-31T23:00:00.000Z, stop: 2025-12-01T14:31:44.004Z)
 |> filter(fn: (r) => r["_field"] == "_value")
 |> filter(fn: (r) => r["_measurement"] == "0_userdata.0.example2" and contains(value: r._value, set: [false, true])) 
 |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value") 
 |> group()
``` 

https://github.com/ioBroker/ioBroker.influxdb/blob/145e59a8d3f1bb0744298e4376bdb0008532b5ce/main.js#L2373

**Comment by tipp88** [comment]
> The error means that there seems to be a value in the DB which is NOT a string, but a boolean and so selection do not work ...
> 
> Else pleas eenable debug log for the adapter AND turn on enhanced logging for this datapoint in the config and post a debug log from such a query ... Then we maybe can look at the reasons for the error

It is a completely new object which has been created as String and logging activated as String. There is not a single value stored as bool, it only 6 values at all:
![image](https://github.com/ioBroker/ioBroker.influxdb/assets/68737433/ace9f6bc-6246-4d28-91b6-84f38de1186f)

![image](https://github.com/ioBroker/ioBroker.influxdb/assets/68737433/741b9ef9-752e-43a8-8cdf-c6c9d498baca)

I think Marc already found the issue. Thanks

**Comment by Apollon77** [comment]
PR merged, thank yopu, preparing release
