### ISSUE TITLE
Influx Data from new Object not logging any longer

### ISSUE THREAD

**Issue by KronenbergSmarthome** [ioBroker/ioBroker.influxdb#405]
I was logging several objects from sourceanalytixs adapter. It worked properly since an half year. I had to make some changes at sourceanalytixs and now I have new objects, but the data base is the same. (For example power consumption per day) I have adjusted/transfered the settings for influxdb datapoints from old objects to the new objects manually. So the Alias-ID´s for all objects are still the same, but I don´t get any new data now. Does it have something to with a hidden ID or property from every object that was connected to the object and now the ID has changed cause it are new objects and now influxdb lost the connection? Connection from influxdb instance and influx database is still ok. I´ve now established a new bucket and changed the bucket in influxdb instance in iobroker to the new bucket. Now I can see the all datapoint is written correctly, but when I switch back to old bucket I can´t see new data. So in my oppinion is has something to do with that in the old bucket there is a hidden property the identifies or connects the object in iobroker with the datapoint in influxdb. In the iobroker object data the is a property "ts": does this identify the unique object and now it changed cause of new object, but still same datapoint? I hope you understand my problem or what I mean.

![grafik](https://github.com/user-attachments/assets/714d7c6e-f87c-4c96-b2e2-855ce51eaec6)

**Comment by Apollon77** [comment]
honestly ... I have no idea and never experienced something like this. So the reason most likely needs to be searched in the inffluxdb and setup there. "ts" is just the timestamp of the last change of the object and not used at all in data historization
