### ISSUE TITLE
Writing Alias Data

### ISSUE THREAD

**Issue by PowerPan** [ioBroker/ioBroker.influxdb#43]
When i want to use an Alias like "Schlafzimmer.Humidity" data is not written to influx.
when i remove the Alias data is immediately available in infux.

no informtions in the logs
what can i do?

**Comment by Apollon77** [comment]
Please enable debug log and use latest version from npm please! then you maybe can see more or send log please

**Comment by DanielHD80** [comment]
Same problem here, no error in log!

**Comment by Apollon77** [comment]
Alias working for me perfectly. Please enable debug logging and provide the log.

**Comment by DanielHD80** [comment]
Genau in der Zeil als das Alias aktiv war, kamen keine Daten rein! Alias rein, kommen sofort wieder Daten an!

![log](https://user-images.githubusercontent.com/5008845/59979809-cadfdd00-95ec-11e9-9ba0-db3dab066741.png)

**Comment by Apollon77** [comment]
Scheinbar läufst Du gerade in das gleiche Issue wie unter https://github.com/ioBroker/ioBroker.sql/issues/81 ... berichtet. Versuche bitte mal ob es nach einem Adapter-Restart auch noch nicht tut oder ob es dann tut. Scheinbar ist da was im argen wenn man während dem Lauf Einstellungen ändert. Ist noch nicht ganz analysiert

**Comment by DanielHD80** [comment]
Auch ein Adapter-Neustart bringt leider keine Änderung...

**Comment by Apollon77** [comment]
Dann bitte debug log vor allem im Unterschied zwischen mit und ohne alias.

**Comment by raintonr** [comment]
The 'Alias' configuration works perfectly for me right now. However, I think the term 'Alias' is misleading because what that really is, is the InfluxDB measurement name.

**Comment by Apollon77** [comment]
Please try new version tomorrow

**Comment by Apollon77** [comment]
Comment and pot reopen if still buggy
