### ISSUE TITLE
Speichern in intervallen nicht möglich

### ISSUE THREAD

**Issue by DanielHD80** [ioBroker/ioBroker.influxdb#49]
Wenn ich kontinuierlich Daten speichern möchte (z.B. alle 60 Sekunden), ist das nicht möglich. Sobald ich den Haken "Nur Änderungen aufzeichnen" setze und einen Intervall bei " trotzdem gleiche Werte aufzeichnen (Sekunden) " definiere, wird nichts gespeichert. Sobald ich den Haken trotzdem setze, geht es.

**Comment by Apollon77** [comment]
Ich verstehe den letzten Satz nicht. Bei mir Turbodiesel seit ewigkeiten. 

Also „nur Änderungen“ und dann im Feld darunter eine Zahl rein. 

Wie genau sieht die Konfiguration aus? Am besten Screenshot bitte

**Comment by DanielHD80** [comment]
Mein Ziel ist die kontinuierliche Speicherung (z.B. alle 60 Sekunden). Wenn ich dann den Haken "nur Änderungen" entferne und unten 60 eintrage, werden keinerlei Werte mehr gespeichert.

Wenn ich nun den Haken bei "nur Änderungen" setze (obwohl ich ja auch bei gleichen Werten speichern möchte!), werden kontinuierlich Werte gespeichert. Auch wenn diese gleich sind!

Trotz Erklärung noch ein Screenshot?

**Comment by Apollon77** [comment]
Das was Du willst geht nicht. Der Adapter ird getriggert wenn sich ein Wert ändert. Je nach Einstellung wird das geloggt oder logging verworfen weil es zB nicht geändert ist oder Änderung zu klein oder so. Das "dennoch nach x Sekunden loggen" greift nur wenn nach einem Logging (oder dem Adapterstart) der Wert nicht neu geloggt wurde weil er sich nicht geändert hat, um für Graphen-Anzeigen Werte zu haben, dann wird er nochmals geloggt. Er wird damit nur beachtet wenn "nur änderugen loggen" gesetzt ist. So ist die aktuelle Funktion.

Für Deinen Usecase ist also "nur änderungen loggen" mit Angabe des Intervalls in S genau das korrekte. Der Wert wird alle x Sekunden geloggt wenn er sich nicht geändert hat, ansonsten sofort falls er sich geändert hat (und dann wieder nach X Sekunden)

**Comment by DutchmanNL** [comment]
der use case und erklaehsrung stimme ich zu, der Lösung nicht ganz :)

das die Einstellung so gesetzt werden muss = kein problem, wir sollten aber auf GitHub (besser noch im admin) einen info dazu geben den auch für mich war es nicht verständlich.

(aus Entwickler sich ja, aus user Sicht nein).

kann mich em eventuell auch annehmen würde mich dan aber freuen wen @DanielHD80 ne Idee hätte was im admin helfen würde es besser su verstehen

**Comment by Apollon77** [comment]
Das besser zu erklären: ack!!

Doku oder im Admin. Bin da für Ideen offen.  Am besten ein issue mit der Idee anlegen. ...
