### ISSUE TITLE
Alterco Shelly - store data for temperature

### ISSUE THREAD

**Issue by ggraziotti** [ioBroker/ioBroker.influxdb#50]
On my raspberry I installed Influxdb and grafana. Configure dB and connection from grafana.
On iobroker I installed, configure and test Influxdb adapter and also shelly adapter.

Now How to read data from shelly and store it for n dB and then make graph, alerts, reports... ?

**Comment by Apollon77** [comment]
Go to Admin - objects and select the very right icon on the line of the objects you want to store the value. The icon is a „wrench“/schraubenschlüsssel. There you can enable data tracking and configure how they should be stored.

**Comment by Apollon77** [comment]
For more more usage questions please use iobroker forum. Thank you.
