### ISSUE TITLE
Store nice data point name for easier querying in Grafana

### ISSUE THREAD

**Issue by CC1337** [ioBroker/ioBroker.influxdb#54]
Hi, 

I am wondering how to get a "nice" datapoint name out of the InfluxDB entries?
For example, I am storing this one:
![grafik](https://user-images.githubusercontent.com/4866744/71751157-f0428300-2e7a-11ea-8cca-5473e285d5e9.png)
and then starting to build a simple visualization in Grafana by querying all temperature sensors by regex /.temperature/ or the like. In my case every series then has this datapoint ID as name. 

How could I query the proper name like "Garage Temperatur temperature" (needs postprocessing of course) then?
Maybe I'm missing something really stupid as I'm new to that topic. 

Especially #32 sounds promising and really handy for smart queries, but that fork did not run on my pi4. And #43 prevents me from using AliasID, although I actually like to have both, a stable ID and a human readble name.

Cheers,
CC

**Comment by raintonr** [comment]
IMHO this is simply a duplicate of #32. If tags could be defined (along with 'Alias', which is actually the measurement name) then everything is flexible enough.

**Comment by CC1337** [comment]
Might be - was just a question. I'll close it then.
