### ISSUE TITLE
'relog' timers don't start until a value actually changes

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.influxdb#57]
I like this 'relog' idea - that values should be written periodically to InfluxDB even though they haven't changed.

However, I note that when the adapter starts it does not actually initiate a 'relog' timer. This timer is only created for each object when that object actually changes.

This can lead to large gaps in values that change slowly after a system reboot/power outage/etc.

When the adapter starts, it should loop through configured objects and set a 'relog' timer on each where applicable.

It is probably true to say that this needs to be done when configuration of an object changes too (start a 'relog' timer or cancel the old one depending on the new configuration).

**Comment by Apollon77** [comment]
Good point ... This might be the core of an issue people saw and I was trying to reproduce ... WIll have a look

**Comment by Apollon77** [comment]
Can you show the config of an affected datapoint please? When I see the code correctly it should work

**Comment by raintonr** [comment]
I don't know what you mean by that. Here's what I did though...

I have a number of objects in ioBroker, one of which is the 'active' status of our heating system. As you can imagine, this turns on/off infrequently so is a good candidate to test relogging. Here is the config for that object:

![image](https://user-images.githubusercontent.com/3794098/74814358-5eda8380-52f7-11ea-86b4-afc8d186f2f9.png)

When I restart the adapter can see the following logged:

```
influxdb.0 | 2020-02-19 08:49:32.332 | info | (21377) enabled logging of HeatingOperating, Alias=true, 12 points now activated
```

However, I wait a long time (20 minutes or more) and do not see any points being written to this measurement. You note that relogging every 300 seconds (5 minutes) is enabled.

I know from past experiments that if I manually turn the heating on a point will be logged.

To me this seems logical as the relog timer is set at line 581 inside the ``pushHistory`` function:

```javascript
adapter._influxDPs[id].relogTimeout = setTimeout(() => reLogHelper(adapter, id), settings.changesRelogInterval * 1000);
```

``pushHistory`` is called from a ``adapter.on('stateChange', (...))`` trigger so it's logical that it's only after an initial change that relogging will commence.

**Comment by Apollon77** [comment]
pushHistory is also triggered from "writeInitialValue" which is done initially and on object changes ...
Could you please turn debug log on and test that again ... In the log your should then see what happens ... mabe we see kore out of this log

**Comment by raintonr** [comment]
I don't know what you intend to happen with that call, but it certainly isn't starting the relog timer.

I turned on debug logging and can see relog timer triggered for other objects, but only after they have changed.

For the HeatingOperating value it simply never gets written.

Check out the attached log.

[iob.log](https://github.com/ioBroker/ioBroker.influxdb/files/4224065/iob.log)

**Comment by Apollon77** [comment]
Hey, When checking your log the datapoint VmcText is working as expected ... Can you compare what is set differetn for that one?

**Comment by Apollon77** [comment]
Ha, I found the reason, expect a new version tomorrow
