### ISSUE TITLE
Aggregate not working if getHistory was used

### ISSUE THREAD

**Issue by Boldie** [ioBroker/ioBroker.influxdb#60]
I just tried to adapt your sample from the main page and edited the id to mine:

```
var end = new Date().getTime();
sendTo('influxdb.0', 'getHistory', {
    id: 'sensors.garden.temperature',
    options: {
        start:      end - 10*60*1000,
        end:        end,
        aggregate: 'max' // or 'none' to get raw values
    }
}, function (result) {
    console.log('Got result: ' + result.result.length);
    for (var i = 0; i < result.result.length; i++) {
        console.log(result.result[i].val + ' ' + new Date(result.result[i].ts).toISOString());
    }
});
```

I got an error from influxdb:  getHistory: "Error: GROUP BY requires at least one aggregate function"

After digging in further, I saw the exected query is incorrect:

```
SELECT * from "sensors.garden.temperature" WHERE time > '2020-04-04T11:38:57.581Z' AND time < '2020-04-04T11:48:59.981Z' GROUP BY time(1200ms)
```

Maybe this must be (but I am not an expert to influxdb):

```
SELECT max("value") from "sensors.garden.temperature" WHERE time > '2020-04-04T11:38:57.581Z' AND time < '2020-04-04T11:48:59.981Z' GROUP BY time(1200ms)
```

which then will produce a result while using this directly on the influxdb cli.

**Comment by Apollon77** [comment]
The reason is that "stop" is missing! I will adjust the readme

**Comment by MK-2001** [comment]
This is needed. You can find it in the readme below the example.

The example is not working without it:
step - (required if aggregate is not "none") used for aggregate functions (max, min, average, total, count) step in ms of intervals

var end = new Date().getTime(); sendTo('influxdb.0', 'getHistory', { id: 'system.adapter.admin.0.memRss', options: { start: end - 3600000, end: end, step: 60000, aggregate: 'average' // or 'none' to get raw values } }, function (result) { for (var i = 0; i < result.result.length; i++) { console.log(result.result[i].val + ' ' + new Date(result.result[i].ts).toISOString()); } });

**Comment by Apollon77** [comment]
Ooohh... my last comment should mean „step“ noch stop ;-)
