### ISSUE TITLE
[Enhancement] Do not trigger on obj change if own custom object === before change

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.influxdb#62]
Behaviour : Adapter is triggered at every object change, this is needed to catch states added to datalogging.

Problem : If adapters (like corona-statistics or others) update their information in object with extend object (or setObject) the adapter triggers every time.

Usually a unneeded setObject (or extend) should be avoided within the adapter itself
( see issue of discovery as example : https://github.com/iobroker-community-adapters/ioBroker.discovergy/issues/75

But in situation like scheduled adapters, this is almost impossible as we would lose name changes or other relevant items.
Option would be to have an getObject first here in th adapter, based on the situation the developer must decide how to implement.

https://github.com/iobroker-community-adapters/ioBroker.coronavirus-statistics/issues/39

Proposed solution : 

- Load all activated states into an object array with their custom[this.instancename]
- at object changes, compare this stored custom object with the triggered one
- Only handle routine for updates in cataloguer if custom object for this namespace is changed.

@Apollon77 please assign to me

**Comment by DutchmanNL** [comment]
relation to all dataloggers : 

https://github.com/ioBroker/ioBroker.influxdb/issues/62
https://github.com/ioBroker/ioBroker.sql/issues/106
https://github.com/ioBroker/ioBroker.history/issues/67

**Comment by Apollon77** [comment]
will be fixed in 1.8.0
