### ISSUE TITLE
Log Error nach Update 1.8.2

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/ioBroker.influxdb#63]
`
host.ioBroker | 2020-04-20 17:25:44.447 | error | instance system.adapter.influxdb.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
-- | -- | -- | --
`
 Kommt auch nach einem User restart.

**Comment by Apollon77** [comment]
Also Instanz läuft nicht oder was soll das issue sagen? Bitte mal mehr log posten

**Comment by vr6syncro** [comment]
das ist leider das einzige was ich bekomme die anderen logs sind alle normal und auch die funktion scheint zu gehen. Der Error kam das erste mal nach dem jscontroller 3 update und auch nur noch wenn ich den adapter neu starte.

**Comment by Apollon77** [comment]
Kann ich mal das komplette Log sehen vom Admin. am besten inklusive noch paar Zeilen davor und danach

**Comment by vr6syncro** [comment]
`

unifi.0 | 2020-04-29 16:56:54.264 | info | (21473) Update done
-- | -- | -- | --
influxdb.0 | 2020-04-29 16:56:48.425 | info | (17683) enabled logging of hm-rpc.0.NEQ1803222.2.ACTUAL_HUMIDITY, Alias=false, 2 points now activated
influxdb.0 | 2020-04-29 16:56:48.424 | info | (17683) enabled logging of hm-rpc.0.NEQ1638739.4.ACTUAL_TEMPERATURE, Alias=false, 1 points now activated
influxdb.0 | 2020-04-29 16:56:48.378 | info | (17683) Connected!
influxdb.0 | 2020-04-29 16:56:48.304 | info | (17683) Connecting http://localhost:8086 ...
influxdb.0 | 2020-04-29 16:56:48.301 | info | (17683) No stored data from last exit found
influxdb.0 | 2020-04-29 16:56:48.271 | info | (17683) starting. Version 1.8.3 in /opt/iobroker/node_modules/iobroker.influxdb, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:56:45.718 | info | instance system.adapter.influxdb.0 started with pid 17683
host.ioBroker | 2020-04-29 16:56:42.679 | info | Do not restart adapter system.adapter.influxdb.0 because desired by instance
host.ioBroker | 2020-04-29 16:56:42.678 | error | instance system.adapter.influxdb.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
influxdb.0 | 2020-04-29 16:56:42.112 | info | (17638) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
host.ioBroker | 2020-04-29 16:56:41.382 | info | stopInstance system.adapter.influxdb.0 (force=false, process=true)
influxdb.0 | 2020-04-29 16:55:50.239 | info | (17638) enabled logging of hm-rpc.0.NEQ1803222.2.ACTUAL_HUMIDITY, Alias=false, 2 points now activated
influxdb.0 | 2020-04-29 16:55:50.237 | info | (17638) enabled logging of hm-rpc.0.NEQ1638739.4.ACTUAL_TEMPERATURE, Alias=false, 1 points now activated
influxdb.0 | 2020-04-29 16:55:50.214 | info | (17638) Connected!
influxdb.0 | 2020-04-29 16:55:50.123 | info | (17638) Connecting http://localhost:8086 ...
influxdb.0 | 2020-04-29 16:55:50.119 | info | (17638) No stored data from last exit found
influxdb.0 | 2020-04-29 16:55:50.087 | info | (17638) starting. Version 1.8.3 in /opt/iobroker/node_modules/iobroker.influxdb, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:55:47.386 | info | instance system.adapter.influxdb.0 started with pid 17638
host.ioBroker | 2020-04-29 16:55:44.944 | info | iobroker exit 0
host.ioBroker | 2020-04-29 16:55:44.352 | info | Do not restart adapter system.adapter.influxdb.0 because desired by instance
host.ioBroker | 2020-04-29 16:55:44.351 | error | instance system.adapter.influxdb.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
host.ioBroker | 2020-04-29 16:55:43.927 | info | iobroker Adapter "influxdb" updated
host.ioBroker | 2020-04-29 16:55:43.871 | info | iobroker upload [0] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/custom.html custom.html text/html
host.ioBroker | 2020-04-29 16:55:43.816 | info | iobroker upload [1] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/custom_m.html custom_m.html text/html
influxdb.0 | 2020-04-29 16:55:43.766 | info | (21579) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
host.ioBroker | 2020-04-29 16:55:43.760 | info | iobroker upload [2] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/de/translations.json i18n/de/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.702 | info | iobroker upload [3] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/en/translations.json i18n/en/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.646 | info | iobroker upload [4] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/es/translations.json i18n/es/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.590 | info | iobroker upload [5] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.534 | info | iobroker upload [6] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/it/translations.json i18n/it/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.478 | info | iobroker upload [7] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.405 | info | iobroker upload [8] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.348 | info | iobroker upload [9] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.289 | info | iobroker upload [10] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
host.ioBroker | 2020-04-29 16:55:43.231 | info | iobroker upload [11] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/index.html index.html text/html
host.ioBroker | 2020-04-29 16:55:43.173 | info | iobroker upload [12] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/index_m.html index_m.html text/html
host.ioBroker | 2020-04-29 16:55:43.114 | info | iobroker upload [13] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/influxdb.png influxdb.png image/png
host.ioBroker | 2020-04-29 16:55:43.008 | info | stopInstance system.adapter.influxdb.0 (force=false, process=true)
host.ioBroker | 2020-04-29 16:55:42.981 | info | iobroker Update "system.adapter.influxdb.0"
host.ioBroker | 2020-04-29 16:55:42.884 | info | iobroker upload [14] influxdb.admin /opt/iobroker/node_modules/iobroker.influxdb/admin/words.js words.js application/javascript
host.ioBroker | 2020-04-29 16:55:38.997 | info | iobroker gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack a
host.ioBroker | 2020-04-29 16:55:38.992 | info | iobroker ERR! build error
host.ioBroker | 2020-04-29 16:55:38.991 | info | iobroker gyp
host.ioBroker | 2020-04-29 16:55:38.989 | info | iobroker make: *** [Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o] Fehler 1
host.ioBroker | 2020-04-29 16:55:38.890 | info | iobroker ../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression before ‘>’ token void InitAll(Handle<Object> exports) { ^../src/linux/BluetoothSerialP
host.ioBroker | 2020-04-29 16:55:38.889 | info | iobroker ../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ declared void void InitAll(Handle<Object> exports) { ^~~~~~../src/linux/BluetoothSerialPort.cc:18:1
host.ioBroker | 2020-04-29 16:55:09.380 | info | iobroker npm install iobroker.influxdb@1.8.3 --loglevel error --prefix "/opt/iobroker" (System call)
host.ioBroker | 2020-04-29 16:55:09.377 | info | iobroker NPM version: 6.14.4
host.ioBroker | 2020-04-29 16:55:08.847 | info | iobroker Update influxdb from @1.8.2 to @1.8.3
host.ioBroker | 2020-04-29 16:55:06.920 | info | iobroker upgrade influxdb
host.ioBroker | 2020-04-29 16:55:05.067 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
dwd.0 | 2020-04-29 16:55:04.512 | info | (17532) Terminated (NO_ERROR): Without reason
dwd.0 | 2020-04-29 16:55:02.278 | info | (17532) starting. Version 2.4.7 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:55:00.072 | info | instance system.adapter.dwd.0 started with pid 17532
unifi.0 | 2020-04-29 16:52:54.236 | info | (21473) Update done
host.ioBroker | 2020-04-29 16:50:05.675 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
dwd.0 | 2020-04-29 16:50:05.151 | info | (17374) Terminated (NO_ERROR): Without reason
dwd.0 | 2020-04-29 16:50:02.451 | info | (17374) starting. Version 2.4.7 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:50:00.083 | info | instance system.adapter.dwd.0 started with pid 17374
unifi.0 | 2020-04-29 16:48:54.245 | info | (21473) Update done
host.ioBroker | 2020-04-29 16:45:11.925 | info | instance system.adapter.daswetter.0 terminated with code 0 (NO_ERROR)
daswetter.0 | 2020-04-29 16:45:11.407 | info | (17224) Terminated (NO_ERROR): Without reason
daswetter.0 | 2020-04-29 16:45:05.902 | info | (17224) starting. Version 2.8.1 in /opt/iobroker/node_modules/iobroker.daswetter, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:45:04.940 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
dwd.0 | 2020-04-29 16:45:04.411 | info | (17209) Terminated (NO_ERROR): Without reason
host.ioBroker | 2020-04-29 16:45:04.124 | info | instance system.adapter.daswetter.0 started with pid 17224
dwd.0 | 2020-04-29 16:45:02.397 | info | (17209) starting. Version 2.4.7 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:45:00.073 | info | instance system.adapter.dwd.0 started with pid 17209
unifi.0 | 2020-04-29 16:44:54.237 | info | (21473) Update done
javascript.0 | 2020-04-29 16:41:18.286 | info | (20757) script.js.User.Telegram.Eingangstür_Wohnung_Telegram_Check: Tür zur Wohnung wurde geschlossen
javascript.0 | 2020-04-29 16:41:15.311 | info | (20757) script.js.User.Telegram.Eingangstür_Wohnung_Telegram_Check: Tür zur Wohnung wurde geöffnet
javascript.0 | 2020-04-29 16:40:55.044 | info | (20757) script.js.User.Cam.Cam_Eingang_neu: Bild 3 gespeichert.
unifi.0 | 2020-04-29 16:40:54.281 | info | (21473) Update done
javascript.0 | 2020-04-29 16:40:53.080 | info | (20757) script.js.User.Cam.Cam_Eingang_neu: Bild 2 gespeichert.
javascript.0 | 2020-04-29 16:40:53.063 | info | (20757) script.js.User.Cam.Cam_Eingang_neu: Webcam Bild per telegram verschickt.
javascript.0 | 2020-04-29 16:40:51.059 | info | (20757) script.js.User.Cam.Cam_Eingang_neu: Bild 1 gespeichert.
admin.0 | 2020-04-29 16:40:33.613 | info | (20623) Repository received successfully.
host.ioBroker | 2020-04-29 16:40:32.675 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
admin.0 | 2020-04-29 16:40:32.577 | info | (20623) Request actual repository...
host.ioBroker | 2020-04-29 16:40:05.565 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
dwd.0 | 2020-04-29 16:40:05.047 | info | (17064) Terminated (NO_ERROR): Without reason
dwd.0 | 2020-04-29 16:40:02.295 | info | (17064) starting. Version 2.4.7 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.16.2, js-controller: 3.0.19
host.ioBroker | 2020-04-29 16:40:00.073 | info | instance system.adapter.dwd.0 started with pid 17064
javascript.0 | 2020-04-29 16:39:24.695 | info | (20757) script.js.User.Cam.Cam_Hof: Bild 3 gespeichert.
javascript.0 | 2020-04-29 16:39:22.706 | info | (20757) script.js.User.Cam.Cam_Hof: Webcam Bild per telegram verschickt.
javascript.0 | 2020-04-29 16:39:22.683 | info | (20757) script.js.User.Cam.Cam_Hof: Bild 2 gespeichert.
javascript.0 | 2020-04-29 16:39:20.701 | info | (20757) script.js.User.Cam.Cam_Hof: Bild 1 gespeichert.
unifi.0 | 2020-04-29 16:36:54.127 | info | (21473) Update done

`
So hier mal etwas mehr vom heutigen Influx Update.
Leider spuckt das ganze wirklich nicht mehr aus.
Adapter läuft ja an sich. Nicht das es am Admin liegt meine das ganze hatte ich mit einem anderen Adapter schon einmal und auch im Forum meine ich was gelesen zu haben,

Kannst auch gerne mal per Anydesk schauen dann komme ich ins Teamspeak.

**Comment by Apollon77** [comment]
Das scheint mir aber alles ok so. Nach einem install wird der Adapter neu gestartet und das ist genau das. Der Adapter bekommt den Befehl sich zu beenden was er tut und wird danach neu gestartet. Die meldung ist strange ... schue ich nochmal an
