### ISSUE TITLE
Error on writePoint

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.influxdb#66]
if the object was a logical value and then became a number, I get this error. changing to other types does not produce results. null is written to the log.
[influxdb_log.txt](https://github.com/ioBroker/ioBroker.influxdb/files/4589446/influxdb_log.txt)
![image](https://user-images.githubusercontent.com/37106885/81228049-0eb9b600-8ff6-11ea-86c8-b1adad22c36c.png)

**Comment by Apollon77** [comment]
Changing data types in influxdb is no good idea because they are "pinned" for each shard as soon as the first value is written. Plese check which value is really in the DB ... I think admin could show some values wrong (and influxdb do not support null at all, so value can not be null).

Also please try latest version (or which version you use?)

**Comment by Anzic23** [comment]
I understand that this is not a good idea, but I had to change the object that is linked to the original one. and there the type changed. I would not like to rewrite it in all scripts where it is used. driver version latest 1.8.4

**Comment by Apollon77** [comment]
But in fact according to your log the adapter did fine, he detected that type difference and fixed it and wrote it with the expected type. So only Admin seems to display wrong values in the table. Please check in DB directly what values are stored. Is it correct there?

**Comment by Anzic23** [comment]
I don't know if the data I got is correct, but it's all I could get. mqtt.3.ESP_Easy_DRAGON.Relay.Switch - this is an original object.
linkeddevices.0.server-room.voda - linked 
![image](https://user-images.githubusercontent.com/37106885/81604941-62067c80-93d9-11ea-8867-47a4036894c7.png)
![image](https://user-images.githubusercontent.com/37106885/81605289-e953f000-93d9-11ea-822f-9f9eab147776.png)
if you tell me exactly how to check the data , I'll check it.

**Comment by Apollon77** [comment]
Try to select raw values plase ... not a "mean"

**Comment by Anzic23** [comment]
there is no such function (raw). there are only these. I made an export, I attach the file.
and it is not clear why this object has two "values"
![image](https://user-images.githubusercontent.com/37106885/81642809-eafad380-942c-11ea-8d8b-e0de7455d4d7.png)
[iobroker.global.linkeddevices.0.server-room.voda.2020-05-12-08-40.zip](https://github.com/ioBroker/ioBroker.influxdb/files/4613608/iobroker.global.linkeddevices.0.server-room.voda.2020-05-12-08-40.zip)

**Comment by Apollon77** [comment]
SELECT * from name ORDER BY time desc LIMIT 100

or such?

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/81694993-b3128100-946a-11ea-9725-d861ad2a4f69.png)

**Comment by Apollon77** [comment]
Sorry bug yes this query makes no sense :-(
And he says whats missing ... he expects ASC or DESC after ORDER BY time(...) and the Fill makes no sense

**Comment by Anzic23** [comment]
I give up. created a new object and reassigned the associated object to it.
