### ISSUE TITLE
Logging - why also info ?

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.influxdb#68]
Hello,
i have many variables to log into an influx database.
In iobroker under LOGGING the adapters write nearly every minute the line which makes my log file very big - sometimes more than 500MB:

> influxdb.0 | 2020-06-01 14:33:13.211 | info | (25509) Store 1002 buffered influxDB history points
> -- | -- | -- | --

I know i can extend it to more stored values (e.g. now 1000 and i can go up to 5000?) but i am asking if it is neccessary to make an info into the logging that the variables are now stored into Influx ? SQL for example doesn't make it.
Is it possible to (manually) disable this logging ?

**Comment by Apollon77** [comment]
SQL is always storing directly (so no batch) - would be the same as if you set in influxdb the buffer to 0.
it is info because the developer thinks it is a relevant information. You are free to increase loglevel wo "warn" for the adapter to not see this anymore
