### ISSUE TITLE
HTTPS - Ignore certificate warning

### ISSUE THREAD

**Issue by KoMa1978** [ioBroker/ioBroker.influxdb#69]
Hi,

can you please add an option to ignore certificate warnings. I want to use https for connection but the certificate chain is not OK. Something like the Grafana option "Skip SSL Verify".

It is working if you edit "/opt/iobroker/node_modules/influx/lib/InfluxRequest.js" and add "rejectUnauthorized: false," to the "this.defaultRequestOptions". So it should be easy to forward this as option from your library (https://github.com/node-influx/node-influx/issues/260).

Without that option  you get an "Error: self signed certificate in certificate chain" during connect. With that option it works fine.

Thanks a lot,
 Marco

**Comment by arteck** [comment]
i think parameter in admin is here the solution

**Comment by KoMa1978** [comment]
I tried to manually add it to the main.js in the "adapter._client = influx({" area of the connect function but this does not work.

**Comment by kennymc-c** [comment]
Any updates on this?

**Comment by mtibke** [comment]
I've used the following workaround by modifying "/opt/iobroker/node_modules/influx/lib/InfluxRequest.js"

```
var request = require('request')
var _ = require('lodash')
var url = require('url')
**const fs = require('fs');**

var resubmitErrorCodes = ['ETIMEDOUT', 'ESOCKETTIMEDOUT', 'ECONNRESET', 'ECONNREFUSED', 'EHOSTUNREACH']

function InfluxRequest (options) {
  if (!options) options = {}
  this.index = 0
  this.hostsAvailable = []
  this.hostsDisabled = []
  this.defaultRequestOptions = {
    timeout: null,
    **ca: [ fs.readFileSync(process.env.NODE_EXTRA_CA_CERTS) ],**
  }
  this.setRequestTimeout(options.requestTimeout)
  this.options = {
    failoverTimeout: options.failoverTimeout || 60000,
    maxRetries: options.maxRetries || 2
  }
}
```

and then added the following environment and bind mount to my docker container:
 -e NODE_EXTRA_CA_CERTS=/etc/ssl/certs/myCA.crt \
 -v /srv/docker/certs/CA/myCA.crt:/etc/ssl/certs/myCA.crt \

**Comment by Apollon77** [comment]
Yes sure, but modifying the used library is not that easy for the adapter ... thne this issue woukd be one for the node-influx package!

**Comment by RkcCorian** [comment]
This would be also something thatI need. I have a self signed certificate which I'm using with ioBroker and grafana. I would like to use this also for influxDB

**Comment by Apollon77** [comment]
We will not work on this anymore for inlfuxdb 1.x ... For InfluxDB 2.x it might be worth

**Comment by RkcCorian** [comment]
That is totally ok as I migrated today to influxDB2 :-) But it would be good to have it there

**Comment by Apollon77** [comment]
What exact error you get?

**Comment by RkcCorian** [comment]
![image](https://user-images.githubusercontent.com/79741077/134054500-20de245d-697b-4ad2-a7a9-af8a6fbbb68c.png)
![image](https://user-images.githubusercontent.com/79741077/134054608-950cfddf-72ae-49d0-b72f-d1524509768b.png)

**Comment by RkcCorian** [comment]
@Apollon77 : Anything that I can do to support? Many thanks!

**Comment by Apollon77** [comment]
It is flagged as enhancement and it will be handled when someone has time.

**Comment by RkcCorian** [comment]
@Apollon77 : Then I hope the best :-)

**Comment by fliix-de** [comment]
Anything we can support? We would like to use InfluxDB2 with ioBroker and SSL. We only have self signed certificates, so that would be the only option. Thanks for this great job so far :)

**Comment by Apollon77** [comment]
Ok, seems to be possible with inlfuxdb 2 https://github.com/influxdata/influxdb-client-js/issues/367#issuecomment-918828164 ... and maybe nodeinflux1 too in a comparable way https://github.com/node-influx/node-influx/issues/260#issuecomment-284209531

**Comment by Apollon77** [comment]
Ok, I checked it: InfliuzxDB 1.x not possible because we use old lib and upgrade is not planned.

For InfluxDB 2.x we can implement it

**Comment by Apollon77** [comment]
Please check upcoming 2.6.0
