### ISSUE TITLE
Backup Funktion

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.influxdb#70]
Hallo,

besteht die Möglichkeit das dem Adapter eine Backup- und Restorefunktion spendiert werden könnte?

Danke

**Comment by Apollon77** [comment]
Was genau meinst Du?
Backup und Restore einer InfluxDB ist denke ein Thema ausserhalb des Adapters

**Comment by MMeinhardt1** [comment]
Ja da ist was dran. Die Idee kam mir aber erst etwas später. Im backitup Adapter auf GitHub ist auch schon ein issues erstellt.
