### ISSUE TITLE
Allow

### ISSUE THREAD

**Issue by alexhk** [ioBroker/ioBroker.influxdb#71]
When I configure history logging via Objects in the web UI, I can set more options than what is available via Javascript.

```
    options: {
        changesOnly:  true,
        debounce:     0,
        retention:    31536000,
        maxLength:    3,
        changesMinDelta: 0.5,
        aliasId: ''
    }
```

I am missing **storageType**. I tried using it in the JS call, but it is being ignored.

Is there another way to create history with custom storageType than manually through the web interface?

In my case I am writing Boolean as Number, so it ends up as 0 or 1 in Influx/Grafana. 

**Describe the solution you'd like**

Having the option available in the Javascript function 👍 

**Describe alternatives you've considered**

Using it without the storageType then after it's all setup changing the type afterwards (ie. on the json/files directly)...

**Additional context**

I frequently have to enable history for a few dozen states, so having a way to do it via JS would be very helpful instead of clicking for 30 minutes and possibly making mistakes. 

Perhaps storageType was just forgotten?

**Comment by Apollon77** [comment]
storageType works ... see testing https://github.com/ioBroker/ioBroker.influxdb/blob/master/test/testAdapter.js#L147 ... maybe it isonly missing inthe documentation?

**Comment by alexhk** [comment]
Thanks Apollon77, my bad. Number has to be in quotes to work, I could have tried that without a lot of yada dada here in the issues. Please close.

`        storageType: "Number",`
