### ISSUE TITLE
Error on writeSeries: Error: {"error":"timeout"}

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.influxdb#76]
**Describe the bug**  
There are many errors in the log, and not all data is written to the database. Some of the data may be lost.
**To Reproduce**  
![image](https://user-images.githubusercontent.com/37106885/101471657-a00c5480-3958-11eb-96ab-cba9dfeb1794.png)

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/101470053-8d911b80-3956-11eb-8f04-896ccf2822af.png)

**Versions:**  
 - Adapter version: 1.9.3
 - influxdb version: 1.8.3
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: Docker container 5.1.0

**Comment by Apollon77** [comment]
timeout means that your influxdb is timing out on storing the data. Please check the DB!
requestTimeout is set to 30s ... why ever it returns after 10s for you already ... but  it is very uncommon that the db needs 10s for 500 values ... normally this is done far faster then 1s! (I use 1000 batches and very fast)
