### ISSUE TITLE
InfluxDB Data Cache

### ISSUE THREAD

**Issue by lindi200000** [ioBroker/ioBroker.influxdb#77]
Halllo,
es währe schön, wenn man wahlweise im Influx Adapter einen "Offline Buffer" aktivieren könnte.
Bedeutet: Die InfluxDB ist mal nicht erreichbar, dann schreibt der Adapter diese Daten lokal in einen Buffer (vielleicht noch einstellbar mit Größe und/oder Einträgen) und wenn die Datenbank wieder da ist, dann werden diese Daten übergeben.
Somit hat man mal einen einen Datenbankausfall keinen Ausfall der Log Werte.

VG
Lindi

**Comment by Apollon77** [comment]
Das passiert alles bereits. Die Buffergrösse kann eingestellt werden. Ich rate eh davn ab es ohne zu verwenden. Wenn nicht erreichbar werden Daten in den Buffer zurückgeschrieben und dieser wird beim Adapter-stop sogar persistiert.

Oder was genau fehlt?
