### ISSUE TITLE
Filter in value table does not work

### ISSUE THREAD

**Issue by EtzeSte13** [ioBroker/ioBroker.influxdb#83]
Using the filter option in the adapter does not work as expected. Filtering values from a determined day does show values with total different timestamp....

**Versions:** 

Adapter Version: 1.9.3
 - JS-Controller version: <js-controller-version> 
 - Node version: v12.19.0
 - Operating system: raspian buster

**Additional context**  
See the details showing this screenshot
![grafik](https://user-images.githubusercontent.com/73318503/106196560-dd9b9a00-61b1-11eb-9d32-5a834176d3b1.png)

**Comment by Apollon77** [comment]
This is an admin issue ... please open issue there - or (i think already existing) add yourself there
