### ISSUE TITLE
After update from 1.9.3 to 1.9.4 some Alias_IDs were ... gone?

### ISSUE THREAD

**Issue by hytrek** [ioBroker/ioBroker.influxdb#86]
Hi there
thanks you very much for the Adapter.
By accident I found out that logging was no longer consistent. From January 26 until beginning of this week no data was collected for some Alias_ID and so visualization was impossible with Grafana.
After digging deeper it looks to me that data from "Plenticore" and "Tankerkönig" was affected only. Data from "Homematic" was fine. (I log data for these 3 adapters only).

I used a snapshot from the 25th (on the 26th I upgraded the influx Adapter from 1.9.3 to 1.9.4) and all Alias_IDs were available again.
Than I used a snapshot from the 26th and than the Alias_IDs were gone (for these two adaptors).. As fare as I remeber correct all I did on the 26th was upgrading Influx.

Please have a look into that 
Thanks

**Comment by Apollon77** [comment]
The influxdb adapter is never deleting custom definitions and if it was only from some adapters please check there. 

Maybe try the old snapshot and just update influxdb? still the same problem? if yes please check the logs. Anything in there which was not before?

In fact betweek 1.9.3 and 1.9.4 only "stop handling" was enhanced

**Comment by hytrek** [comment]
OK Thanks for your response... It must have been my mistage than... Appologies!

**Comment by Apollon77** [comment]
No problem ... would be interesting what the reason was. So please come back when you have more infos

**Comment by hytrek** [comment]
Appollon, as I wrote. I treid to nail it down by using a snapshot from the day before and all was good. I have no clue and really wonder what happened... I again typed in the Alias_IDs and it workes, except the days in between are missing... I trust you are right and assume, I did it... ??? HEADSCRATCH
