### ISSUE TITLE
Retention time

### ISSUE THREAD

**Issue by stenmic** [ioBroker/ioBroker.influxdb#90]
I always thought that with the "Vorhaltezeit" option, the measurement data would be deleted from the database after this time had elapsed. 

In this example after 2 weeks 
![Image 094](https://user-images.githubusercontent.com/56360313/111020212-80a41e00-83c4-11eb-8b09-bc6584524e67.jpg)

Unfortunately this is not, all measuring are available since the beginning of the recording. 
![Image 095](https://user-images.githubusercontent.com/56360313/111020223-96194800-83c4-11eb-804d-19e432fde281.jpg)

think i wrong or is it a bug?

Since I don't want to bloat my database and I have a lot of "short traks", it would be nice if it could be set how long data should be in the database.

**Comment by hacki11** [comment]
See #29

**Comment by Apollon77** [comment]
exactly, thats why closed as duplicate
