### ISSUE TITLE
Timeout fehler influxdb

### ISSUE THREAD

**Issue by ManuelK83** [ioBroker/ioBroker.influxdb#96]
Hallo bekomme seit irgend einem update von IO Broker eine Fehlermeldung von der Influxdb. (Zumindest ist mir es erst da aufgefallen)
Ich kann nicht genau sagen von welchem, da ich mehrere durchgeführt habe. 
Benutzte die DB für Grafana.

Hier der Fehler. 
Dieser kommt bei allen Aufzeichnungen. Aber auch nicht immer. 

influxdb ist auf Version 1.83
influx Adaper ist  aKtuell 1.94
Node.js =v10.23.0
NPM=6.14.8
 JS-controller= 3.2.13
`

influxdb.0 | 2021-04-13 19:25:51.417 | info | (24037) Add point that had error for viessmannapi.0.heating.circuits.0.circulation.pump.status to buffer again, error-count=1
-- | -- | -- | --
influxdb.0 | 2021-04-13 19:25:51.414 | warn | (24037) Error on writePoint("{"value":"on","time":"2021-04-13T17:25:41.175Z","from":"system.adapter.influxdb.0","q":0,"ack":true}): Error: {"error":"timeout"} / "{\"error\":\"timeout\"}\n"

`Hoffe es kann mir einer sagen was da los ist.

**Comment by Apollon77** [comment]
Das bedeutet das deine influxdb nicht schnell genug antwortet. An sich ist der Timeout nicht so niedrig ... also Checke mal die influxdb

**Comment by jp112sdl** [comment]
Falls hier noch mal jemand drüber stolpert... Bei mir tritt der Fehler seit Umstieg von Rpi 3B+ auf Rpi 4 auch auf.

Abhilfe schaffte die Lösung : https://github.com/influxdata/influxdb/issues/8036#issuecomment-875697382

**Comment by BenAhrdt** [comment]
Also ich habe den Fehler immer wieder mal so nach einer Woche... dann kann man auch influxdb oder den Adapter neu starten wie man will, das "Problem" besteht weiter so ca. eine Woche, danach geht es wieder für ca. eine Woche.
Ich habe schon die env Variable der influxdb (Docker) auf 0 gesetzt und ihn damit deaktiviert. es geht trotzdem nicht.
Die Daten kommen zwar in der influxdb an, aber der Log wird entweder mit warnings überflutet, oder wenn man nur errors logt, dann sieht wan, wie alle 3-5 min der Adapter neu  gestartet wird.

![image](https://github.com/ioBroker/ioBroker.influxdb/assets/92173565/0c6b6456-2426-45a0-aa6e-156cd6775af7)
